### ISSUE TITLE
DwC Georeference verbatim fields incorrectly mapped

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2344] opened 2021-07-14 20:44 UTC
DwC decimalLatitude/Longitude are mapped to verbatim latitude/longitude. 

Meanwhile, DwC verbatimLatitude/Longitude are not mapped to TW fields.

**Comment by LocoDelAssembly** [comment] 2021-07-14 20:51
Duplicate of #2097. Lets continue discussion there.

**Closed by LocoDelAssembly** 2021-07-14 20:51 UTC
Labels: bug
