### ISSUE TITLE
FieldOccurrence Model  [Edit.  Was: How do we register other Basis of record such as Checklist/Literature/Map or a Simple Field Observation.]

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#3386] opened 2023-04-25 18:17 UTC
### Feature or enhancement

I just came up with a new published checklist. The only specimens captured were the ones that needed further work to be identified. So most of the records that this work provides with specific coordinates do not correspond to preserved specimens.

In Species Files we have many basis of record available to choose from.

We realize now that no matter what is selected in that field, TW creates a "Basis of Record: Preserved Specimen" for all the records. Not only that is not correct but we also need the option to create new Specimen Records using TW and be able to choose the right case (Such as a Checklist, or map for records).

### Location

Comprehensive specimen digitization task or a new one?

### Screenshot, napkin sketch of interface, or conceptual description

![image](https://user-images.githubusercontent.com/63611746/234364400-74613230-ad2b-4bc2-b7b5-9fcfa7264a70.png)
Which would be the best practice for these cases?

### Your role

Curator

**Comment by mabecabrera** [comment] 2023-04-27 12:47
We also have the situation that currently the records that in OSF correspond to a chacklist, personal observation, etc., in the migration are incorporated into TW as Preserved Specimen. But this is not real.

**Comment by mjy** [comment] 2023-05-15 13:28
Checklists and Maps are not indicated specifically but referenced as Sources in the Citation for an AssertedDistribution.  This will generate an alternate Occurrence type.

The additional model, that we'll turn this issue into, is FieldOccurrence.

**Comment by mabecabrera** [comment] 2023-08-28 19:42
We need this for us and the people that have Grants from OSF and enter georeferenced photographyc records.

**Comment by mabecabrera** [comment] 2023-09-01 19:53
We have people with grants that need to add images and specimens observed in the field but not collected.

@mjy what do you think of this another **CRAZY** way?

What if they add this records as Collection Objects but always with a TAG like **Field Occurrence** to find them easier later.  We can then make a list of all of them with a filter and download them in DwC format to make an import later. And also **DELETE** them from the filter so we can add them later using the DwC import task.

They also have images associated to them. They might add those pictures to the corresponding OTU and TAG them with some code we invent for the collectinon object? So we can later make the connections between the collection objects and their depictions.

I know it is crazy, but to have them in an excel file for more time, I think it will be frustrating for them not being able to add their work. And they could create this DwC excel though TW.

WHAT DO YOU THINK? TOO CRAZY?

**Comment by mjy** [comment] 2024-02-27 19:16
Duplicate of #1643, which should land shortly.

**Closed by mjy** 2024-02-27 19:16 UTC
Labels: enhancement, question, model
