### ISSUE TITLE
Homonymy cross-reference problematic

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1470] opened 2020-05-03 12:11 UTC
Cross-referencing of **_homonymy_** works differently from **_synonymy_** in TW (and it shouldn't) and has problems.

If genus Aus is a homonym of Bus, then Bus is ALSO a homonym of Aus. Regardless of which one is junior and senior. BOTH are homonyms (of each other).

In **Edit taxon name**
Whenever I enter in the **Relationship** box that Aus is a homonym of Bus, I assumed that this should be automatically cross-referenced by the system stating that Bus is a homonym of Aus (as it happens with the synonymies). 

See here: _Celebesia_ Roewer, 1949 is a junior homonym of _Celebesia_ Riley, 1918 and it duly appears in Browse nomenclature (line 3 from top):

![image](https://user-images.githubusercontent.com/46284943/80913580-feff5080-8d1b-11ea-8baf-0f71a12181bb.png)

But when I looked at Celebesia Riley, 1918, there was no indication of this homonymy. I  had to input this manually, so it appears on line 2:

![image](https://user-images.githubusercontent.com/46284943/80913613-47b70980-8d1c-11ea-9871-6bb838bf97ef.png)

Then I get a message which doesn't make sense:

![image](https://user-images.githubusercontent.com/46284943/80913628-63221480-8d1c-11ea-9cfc-20615fdf86f4.png)

This message has three errors:

1) It uses the word **_homonym_** when the intended sense is **_junior homonym_**.

2) Not all homonyms have replacements. There may be synonyms competing for precedence, which make a substitute unneeded (superfluous). And of course, a senior homonym doesn't need a replacement per se.

3) By being a senior homonym, Celebesia Riley, 1918 should be valid. In this specific case there is yet another homonym in Orthoptera, which I will duly add later. I just wanted to highlight this inconsistency in the system.

**Comment by proceps** [comment] 2020-05-04 18:42
All relationship are two directional by definition. But we display the relationship in one place only. Where it is more appropriate. In the case of homonyms, it is displayed together with a junior homonym. The place where it is more important to justify invalid status of the name. We definitely can display the label in both places for junior as well as senior homonym, but honestly, I did not see any useful information to show the homonymy for senior names. I could not recall seeing any catalog doing it. So the first image you uploaded represent the correct recording the homonymy in the database. If it is absolutely necessary, we can show senior homonyms as well, but this is not a bug, this is a display issue. All information is available and stored in the DB correctly.
For the senior synonym, you are not expected to provide this information the second time. That is why you see all those conflicting messages.
Not all senior homonyms are valid, it could be in tern be a junior synonym of another name, so you cannot make this assumption.
A substitute name is a correct term which covers both a replacement name (nomen novum), and a junior synonym name, which is validated after the homonymy was discovered (Art. 60.1).
Remember, all Taxon Name Relationships are two directional. Synonym (junior/senior), homonym (junior/senior), type species, original genus. In each case, there are two names involved and the status could be read in both ways. But when the species is a type for a genus, we display it only on the genus page, but not on the species page, although in theory we can.

**Comment by adrik29** [comment] 2020-05-04 19:53
Thanks, Dmitry, for the lengthy explanation.
And of course, my bad -- a senior homonym doesn't have to be valid... It may be a junior synonym of something else.
I just found it a bit inconsistent to cross-reference the synonyms but NOT the homonyms.
I personally like to cross-reference everything, but I agree with you that marking the SENIOR homonym is not critical, only the junior.
Stay safe,
Cheers

**Comment by proceps** [comment] 2020-05-04 19:57
@adrik29 should we keep the issue open, or close it?

**Comment by adrik29** [comment] 2020-05-04 22:19
@proceps you may close it -- I'm just adapting to the system and in this specific case I will not pursue further the matter of cross-referencing the senior homonyms.

**Closed** 2020-05-04 22:26 UTC
