### ISSUE TITLE
Collection object filter is not finding containerized identifiers

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1240] opened 2019-12-16 19:21 UTC
**Describe the bug**

Collection object filter is not finding containerized identifiers when searching by identifier or identifier range. 

**To Reproduce**
1. When I go to "Collection Object Filter" task.
2. Then I search for an identifier or range of identifiers, where the identifier I am searching for is "containerized".
3. And I search.
4. Get no results for that identifier. But I can find the specimen if I search by a different attribute, e.g. Taxon name. 

**Expected behavior**
Should be able to search for an identifier even if containerized. 

Collection object in question (Insect Collection 39678)
![image](https://user-images.githubusercontent.com/11411328/70935677-54a1bd80-2006-11ea-80c7-e23de0c27a0c.png)

Blank namespace and partial matching search:
![image](https://user-images.githubusercontent.com/11411328/70935743-80bd3e80-2006-11ea-8c6d-54cd3628f72c.png)

Results (note lack of requested identifer):
![image](https://user-images.githubusercontent.com/11411328/70935777-96caff00-2006-11ea-8985-44ea3f1f27cb.png)

INHS Namespace and "range of identifiers" search:
![image](https://user-images.githubusercontent.com/11411328/70935953-f6290f00-2006-11ea-8636-717becefaae9.png)

Results (note lack of identifier 39678):
![image](https://user-images.githubusercontent.com/11411328/70935933-ead5e380-2006-11ea-92cd-cff223296479.png)

**Environment (please identify where you experience this bug:**
- Production
- Chrome

**Comment by tmcelrath** [comment] 2019-12-16 19:25
Note that containerized specimens still show up when searching by other attributes, e.g. Taxon name.

**Comment by mjy** [comment] 2019-12-16 20:31
Techncially not a bug, we didn't initially intend for this.  Marking as enhancement.

**Comment by mjy** [comment] 2023-02-27 18:32
Coming in unified.

<img width="1627" alt="Screenshot 2023-02-27 at 12 31 10 PM" src="https://user-images.githubusercontent.com/22600/221652126-bae8b869-046c-4c3c-a169-11e77e8585c3.png">

**Closed** 2023-03-07 16:12 UTC
Labels: enhancement
