### ISSUE TITLE
Simple upload bug

### ISSUE THREAD

**Issue by teleaslamellatus** [SpeciesFileGroup/taxonworks#2083] opened 2021-03-03 21:29 UTC
**Describe the bug**

Tried to upload this [nomenclature](https://docs.google.com/spreadsheets/d/1lpkK98dpgvtUtecVPiU0VBDfN7ajqGJ1UC-P8_KGtEQ/edit?usp=sharing) file to my Aphanogmus sandbox. It has previewed the file OK, 4379 names to be added. I have selected Tabanidae as the parent. After a while, it received an error message "504 Gateway time-out nginx/1.14.2".

The taxon names were seemingly created OK, but I see now 4520 names (I had manually created 3 before the upload).

Thanks!

István

**Comment by mjy** [comment] 2021-03-03 21:31
Good catch. @LocoDelAssembly at some point we'll move all batch loaders into the DwC framework and this will be resolved.  @teleaslamellatus for now understand that at commit the import is executed, and will complete in the background.

**Comment by LocoDelAssembly** [comment] 2021-03-03 21:40
@mjy yes, the future plan is to make all batch loaders produce subclass instances of `ImportDataset` and corresponding subclass rows of `DatasetRecord`. From DB-perspective staged-imports branch pretty much has all its needed, but of course UI, controllers and models for specific batch loaders are still needed.

**Comment by mjy** [comment] 2024-03-25 15:08
Duplicate of #897

**Closed by mjy** 2024-03-25 15:08 UTC
Labels: bug
