### ISSUE TITLE
Task - Uniquify Serials

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1119] opened 2019-10-11 17:12 UTC
I want to be able to uniquify similar serials while preserving slight variations in serial names so that I can search by them. Have flag/warning for linking "preceded by" and "succeeded by" relationships.

**Comment by proceps** [comment] 2020-06-24 17:08
related to #1117

**Comment by proceps** [comment] 2020-06-24 17:08
I need this functionality too

**Comment by mjy** [comment] 2024-09-17 15:31
Duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/970.

**Closed by mjy** 2024-09-17 15:31 UTC
Labels: task
