### ISSUE TITLE
taxon name cannot be deleted

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#3541] opened 2023-09-04 15:51 UTC
In "Edit taxon name" I want to delete it, but it says there is a relationship:
![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/a308c30f-0b25-4f0b-9f83-2ed95f035847)

This is not true, I deleted the relationship. It was a synonym (migration error), now it's valid, although the Soft Validation still thinks it is a synonym:
![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/780ecd4f-d60a-4331-ac8a-14778f3353ae)

Is this a bug?

**Comment by LocoDelAssembly** [comment] 2023-09-04 16:03
@typophyllum please provide the taxon name you are trying to delete.

**Comment by proceps** [comment] 2023-09-04 16:26
Please visit Wednsday meeting for an assistance. It is not a bug. The name cannot be deleted if there is a related OTU (is to be deleted or reassigned to another TaxonName first). Or there are other related records, you can explore related records using this task:
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/15a04dd9-17ab-465e-a972-1ace3596068d)
All related records have to be resolved (moved to another taxon name) before a record could be deleted.

**Closed by proceps** 2023-09-04 16:26 UTC

**Comment by typophyllum** [comment] 2023-09-04 17:37
Thanks. Now I managed to destoy it.
