### ISSUE TITLE
Task - Browse (search) sources results need visual improvement

### ISSUE THREAD

**Issue by anadm** [SpeciesFileGroup/taxonworks#778] opened 2019-02-04 18:54 UTC
When I go to the browse (search) sources, and I search for a reference, I get a list of results. 
As user I can easily identify where the annotator is and the link for "citations by source". 
However, if I want to edit the reference itself (say, add italics) I need to mouse over it, and double-click it. Because the hover color is soft, I can barely see it. Also, need for double-clicks is not standard behavior for browser navigation.
There should be a button or improve the hover behavior (underline, maybe?) so user understands clicking there takes them to go to the "show/edit" screen. 
Also, after all this work when I get to that "show" screen and press up/down keyboard arrows to see all that information (that screen is, expectedly, long!), that should scroll the page, not go to the next reference!

**Comment by mjy** [comment] 2019-02-19 20:06
We do intend to push controlls beyond what is expected in general in a browser, this means some new behaviour will crop up.  As long as it doesn't hijack existing behaviour I don't necessarily see this as a bad thing.

Try right clicking.  The double-click is a shortcut.   What we want to do is have all tables get a set of behaviours, the alternative is to add columns (4, 5, more) that contain icons/links.  Getting that all smoothed out will take a bit.

We do need to an option disable arrow navigation, or maybe a helper key added on.

M

**Comment by mjy** [comment] 2019-03-01 20:40
Disable arrow is duplicate of #710.

Remaining navigation will be handled when #737 is complete.

**Closed by mjy** 2019-03-01 20:40 UTC

**Comment by anadm** [comment] 2019-03-03 21:26
on this note, I noticed there is no hover over behavior on the results table. We should get it so one knows that the references are double-clickable.
