### ISSUE TITLE
New Combination-gender issues

### ISSUE THREAD

**Issue by MMCigliano** [SpeciesFileGroup/taxonworks#327] opened 2018-02-07 18:12 UTC
I have one doubt regarding the New Combination.
If for instance, I want to create a new combination Ponderacris vittata  for the name  Dichroplus vittatus Bruner. But since I have adjusted the ending of the specific name to the gender of the generic name, the search in the New Combination does not find the specific name.

**Comment by mjy** [comment] 2018-02-07 18:22
This is exactly (one) of the issues we've noted.  Fixes are non-trivial,
but planned.  We may have to come up with a secondary form that handles
these "edge" cases.

**Comment by mjy** [comment] 2018-02-08 15:16
Duplicate of #315

**Closed by mjy** 2018-02-08 15:16 UTC
