### ISSUE TITLE
[Bug]: Basic paper catalog: some geographic units are not parsed

### ISSUE THREAD

**Issue by Omias** [SpeciesFileGroup/taxonworks#3499] opened 2023-07-24 14:36 UTC
### Steps to reproduce the bug

```bash
1. geographic units Jawa, West Himalaya, Laos are not parsed in Basic paper catalog
2.
3. 
...
```

### Environment

Production

**Comment by mjy** [comment] 2024-09-27 13:36
Duplicate of #3392

**Closed by mjy** 2024-09-27 13:36 UTC
Labels: bug
