### ISSUE TITLE
Estimate Person's year active range in uniquify people task when not given

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2767] opened 2022-01-14 21:54 UTC
### Feature or enhancement

How hard would it be to generate an estimated activity range for people based on CO/CE data?

After importing a bunch of DwC records, there are often multiple names for a person (eg. with/without first name, initials, etc.) 

A quick way to confirm that they are the same person is the range of years they were active. 

By looking at Collector and taxon determination dates, we could find the earliest and latest dates they were active.

### Location

Uniquify people

**Comment by mjy** [comment] 2022-01-14 21:59
Part of this is aready done I think.  We update person active estimates after save.  There should be specs on roles IIRC.

To use this data to confirm you would have to create, perhaps an in memory Person, then a method on @person to compare, using active datas, against an arry of targets.

**Comment by LordFlashmeow** [comment] 2022-01-17 22:37
Maybe even just a task/action would be sufficient -- calculate missing active dates.

**Comment by mjy** [comment] 2022-01-23 16:14
The more I think about this the more it should already be done (i.e. we already have this in code) if there is any data at all.  All Roles trigger a check and update IIRC, so there wouldn't be any extra data to estimate from.  If we can confirm that some role is not, for example write a spec for colleting event that has any year information in parsed, add a collector, and check their active dates, then we can approach this issue again.

**Comment by mjy** [comment] 2022-03-31 15:03
Duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/2854.

**Closed by mjy** 2022-03-31 15:03 UTC
Labels: enhancement
