### ISSUE TITLE
Model - Descriptors - Add two new column names.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#594] opened 2018-10-26 21:30 UTC
* Name of the descriptor for autogenerated description
* Name of the descriptor for the interactive key

Envisioned functionality, they are the same by default. But could be readjusted for better reading in different interfaces.

**Comment by mjy** [comment] 2018-10-26 21:38
Duplicate of #443

**Closed by mjy** 2018-10-26 21:38 UTC
Labels: blocker
