### ISSUE TITLE
Individual contributions of members of my project

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1746] opened 2020-09-17 15:03 UTC
Is there a way to count and/or to see how much each of my team members has done [lately/ever]?
I know that I can go to the "list" feature of many items of the "Data" tab.
But could I see more general stats?

**Comment by mjy** [comment] 2020-09-17 15:12
Duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/50

**Closed by mjy** 2020-09-17 15:12 UTC
