### ISSUE TITLE
[Bug]: Verbatim Trip Code is still "Trip Code" and not "Field Number"

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#4060] opened 2024-09-20 14:53 UTC
### Steps to reproduce the bug

```bash
IN CSD in Verbatim CE it still says "Trip Code" not Field Number.
```

### Environment

Production

### Version

0.44.0

### Browser Used

Firefox

**Comment by mjy** [comment] 2024-09-20 19:08
Duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/4058

**Closed by mjy** 2024-09-20 19:08 UTC
Labels: bug
