### ISSUE TITLE
Task - New extract - enchanced information

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2271] opened 2021-05-24 23:22 UTC
as a user, I would like to see enchanced information on some of the fileds (once selected):
for OTU, I would like to see present valid name and classification
for Collection object, I would like to see complete collecting event label.

This could be populated as a separate Task as well (Browse extracts).

**Comment by mjy** [comment] 2021-06-02 22:28
Duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/2283

**Closed by mjy** 2021-06-02 22:28 UTC
Labels: enhancement
