### ISSUE TITLE
Data Notes. The Search is finding some OSF notes but does not find others.

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#3071] opened 2022-08-10 19:37 UTC
### Feature or enhancement

E.g. 
In the process of curating the data imported from OSF, I need to edit some terms used on the notes of some citations, so I was hoping to find all the notes that use an specific term in the Data card "Notes".

The Taxon Name I was working on is the genus _Amphinotulus Günther, 1939 _
![image](https://user-images.githubusercontent.com/63611746/184004202-738b5b82-1a92-4068-9438-689895bf7663.png)

If I look for the note in the first citation, TW gets me the exact one first.
![image](https://user-images.githubusercontent.com/63611746/184004512-aa39a4fb-c18b-45c2-b9b7-5cbd13fb5599.png)

But then if I look for the next one: "synonymization with Salomonotettix not possible"
![image](https://user-images.githubusercontent.com/63611746/184004629-c94c18e6-4661-4835-b286-73dcbf78943f.png)

Then TW gets me results that have nothing to do with this note.
![image](https://user-images.githubusercontent.com/63611746/184004748-1c2e5199-1e18-4026-99f8-7cb29b609565.png)

Why is that? 

### Location

Data - Notes

### Your role

Curator

**Comment by proceps** [comment] 2022-12-07 16:20
it is not perfect, but at the moment, you can use Browse annotations interface. Search for Notes on citation, which could be downloaded as csv file and use Excel filterring to find relevent notes.

**Comment by proceps** [comment] 2022-12-07 16:30
duplicate of #2771

**Closed by proceps** 2022-12-07 16:30 UTC
Labels: enhancement
