### ISSUE TITLE
LepIndex - duplicate Sources

### ISSUE THREAD

**Issue by AdrianHine** [SpeciesFileGroup/taxonworks#33] opened 2016-10-17 20:29 UTC
For some sources there are duplicates e.g. ‘Bales 1909’, ‘Barragué, 1954’, ‘Bernardi, 1953’. The first one created on 11/09/2016 and the second record created on 22/09/2016 (the only difference is that the later version is marked up as ‘This source is used in another project.’).

**Comment by mjy** [comment] 2016-10-17 21:23
This is (almost completely) an artifact of the sandbox.  We just build the same import against it again and again.  Once we go to production those references will (likely) not be there, so the problem is drastically reduced for these early imports.

**Comment by mjy** [comment] 2016-12-07 18:43
Closing this as resolved.

**Closed by mjy** 2016-12-07 18:43 UTC
