### ISSUE TITLE
Occasional super long OTU retrieval

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1642] opened 2020-08-05 22:00 UTC
**Describe the bug**
Sometimes, using auto-complete in the taxon names field just takes forever and ever and continuously spins. 

**To Reproduce**
1. When I am in Comprehensive.
2. Then I go to add determinations.
3. And I enter any text e.g. "Scarabaeidae"
4. Sometimes, it will pull up results in <1 second, but then randomly, it will take minutes to find this.
5. If noticed, can just modify search by one or two characters and the search will complete much faster. 

**Expected behavior**
Autocomplete search options for determinations should always be recovered very quickly. 

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by tmcelrath** [comment] 2020-08-05 22:01
Log reference: 
"I'm now seen very large times to render taxon_names/select_options.json.jbuilder (Duration: 23219.5ms | Allocations: 7141687)."

**Comment by proceps** [comment] 2020-08-05 22:07
It happens occasionally in any TaxonName or OTU autocomplete search in different tasks (TN browse, TN edit, comprehensive, asserted distribution, etc.). It feels like like the autocomplete search is timed out within 5 seconds. So, if I do not get a result within 5-10 seconds, the spinner never stops. Modifying the search in one letter restarts the search (you can even put the same search term). I cannot replicate this in localhost. But very common issue in production. Too many requests to the DB at the same time?

**Comment by LocoDelAssembly** [comment] 2020-08-05 22:42
Could be that making a different search alters your recent history causing the problematic entry to be evicted so you get a shorter delay? From the logs it looks it actually completes, but I doubt someone waits have a minute for the autocomplete to finish (but perhaps front end code timeouts too).

**Comment by LocoDelAssembly** [comment] 2020-08-05 23:07
I think I narrowed down the log entries to this particular problem (one of the examples anyway). I'm afraid I cannot upload here because I might leak sensitive data, but at least two instances of large time (24 and 28 seconds) occurred with `/taxon_names/select_options?klass=TypeMaterial&target=TypeMaterial&nomenclature_group[]=SpeciesGroup`. However, if I go to production, select a project and paste the URL nothing happens and completes very fast, so it is very sensitive to recent user's activity it seems.

**Comment by mjy** [comment] 2020-08-05 23:56
We need to double check the AJAX pattern being used too, to ensure requests
are properly cancelling/ignored once new ones go out?  IIRC something in
particular had to happen in mx for this to work right.

**Comment by proceps** [comment] 2020-08-06 02:09
It does not relate to a particular name or rank group. The issue just randomly appear. I believe I have this issue less common at night and weekends, presuming less people online. But again, this feeling could be subjective.

**Comment by mjy** [comment] 2020-08-06 02:54
Wait- @tmcelrath determinations queries otus, not taxon_names.  Screenshot of the autocomplete causing problem?

**Comment by mjy** [comment] 2020-08-06 03:12
There are multiple issues going on here, perhaps 3.  Let's clarify and create new ones before we pursue further:

* Potential issue with OTU saving
* Potential issue with taxon_names select_optoins
* Potential issue with OTU autocomplete

So:

* @tmcelrath please chime in with the specific for #1642.  
* @proceps please add specific details (or create new issue).  Select options is fired in TypeMaterial for taxon names here (that's it).  Where are you when this happens?

**Comment by mjy** [comment] 2020-08-06 03:15
For the record at least one thing is broken @jlpereira.  `/taxon_names/select_options` doesn't take `klass` or `target` (it takes nothing).

**Comment by tmcelrath** [comment] 2020-08-06 15:27
![image](https://user-images.githubusercontent.com/11411328/89550561-5efc0c00-d7cf-11ea-93aa-b2a64e6a03e7.png)
Been getting it here, and in the OTU field below in Biological Relationships.

**Comment by tmcelrath** [comment] 2020-08-06 15:28
This is not about saving OTUs - just with long autocomplete requests.

**Comment by proceps** [comment] 2020-08-06 15:33
I am talking about OTU and TN search boxes. I do not use search boxes much in the comprehensive task, since proper names are populated as recent when I come from Browse TN to enter the type specimen, but all other tasks when you search for a TN (Browse TN, Edit TN (parent, related taxon name, name in original combination), New combination), or when I search for OTU (New asserted distribution, OTU radial (biological association, asserted distribution), comprehensive for biological association). The issue for me is not related to saving the record. I am talking only about search boxes where you are trying to retrieve the TaxonName or OTU. It is not a permanent problem. As @tmcelrath mentioned, sometimes search return results withing a split of second when you stop typing the search term. Sometimes it takes forever. In all cases, I know that the name is in the database, and I get the result eventually, if I add or delete one character from the search term.

**Comment by tmcelrath** [comment] 2020-08-06 16:09
I managed to get a video recording and timestamp of the error: https://www.dropbox.com/s/nnh57s9c00aer3u/Screen%20Recording%202020-08-06%20at%2010.57.46%20AM.mov?dl=0

**Comment by tmcelrath** [comment] 2020-08-06 16:12
Or: https://vimeo.com/445270720 (might not be done converting yet)

**Comment by LocoDelAssembly** [comment] 2020-08-06 22:23
Sorry, missed this.

The earliest log entries I have (filtered with `| grep "term=cur"`) are 
```
10.32.0.1 - - [06/Aug/2020:15:59:57 +0000] "GET /otus/autocomplete?term=curculionidae HTTP/1.1" 200 295 "https://sfg.taxonworks.org/tasks/accessions/comprehensive" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36"
[taxonworks-66c974cc4b-rzzm8] I, [2020-08-06T15:59:55.340964 #5756]  INFO -- : Started GET "/otus/autocomplete?term=curculionidae" for x.x.x.x at 2020-08-06 15:59:55 +0000
```
(which if I seen correctly it is the same time @tmcelrath finished typing at the end of the video), so potentially this could be that the request for "curculioni" is not being actually sent and it is a front-end issue.

If anyone gets this problem please open the console and look for errors. @jlpereira any idea what could be wrong?

Also, as another note: The logs I've mentioned earlier are unrelated to this autocomplete.

**Comment by jlpereira** [comment] 2020-08-06 22:29
I will check the autocomplete. Maybe the problem is there

**Comment by LocoDelAssembly** [comment] 2020-08-06 22:42
Hold!

When checking the logs at the proxy an entry appeared which is placed later in time but within the timeout tolerance:
```
x.x.x.x - - [06/Aug/2020:11:07:11 -0500] "GET /otus/autocomplete?term=curculioni HTTP/1.1" 504 585 "https://sfg.taxonworks.org/tasks/accessions/comprehensive" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36"
```

There has been some pod restarts so that probably explain why I don't have application logs for this.

**Comment by LocoDelAssembly** [comment] 2020-09-02 13:18
Potential fix: https://github.com/SpeciesFileGroup/taxonworks/pull/1698

**Comment by mjy** [comment] 2020-10-13 14:18
Can we close this now?  I think @LocoDelAssembly work on Biodiversity seems to have resolved this?

**Comment by tmcelrath** [comment] 2020-10-13 14:26
Go ahead and close and if I see it again I'll ask for it to be reopened.

**Closed** 2020-10-13 14:29 UTC
Labels: bug
