### ISSUE TITLE
[Bug]: Task - Filter Collection Objects/Collecting Events - Bugs

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3231] opened 2022-12-12 22:56 UTC
### Steps to reproduce the bug

```bash
1. Filter CO or CE
2. begin typing any collector name in 'Collectors' field

Typeahead works incorrectly in the Collectors text box (and perhaps elsewhere). For example, when typing “R.A. Johnson”, “Johnson” or “R.A.” the dropdown menu does not show “R.A. Johnson” as a possible collector. Typing “R.A. Johnson” entirely yields two “R.A. Johnson” collectors, as well as “Johnson, Harry L”. Typing “Johnson, R” brings up “Harry”, “Clifford”, and “Mrs.”, as well as the two “R.A” entries. Fix: Typeahead results should find collector name easily by ether initials or last name. See screenshots below
```

### Screenshot

![collector1](https://user-images.githubusercontent.com/74991451/207170533-9e0f206b-e496-4ae8-9e04-a51324e5f760.jpg)

![collector2](https://user-images.githubusercontent.com/74991451/207170568-89f2cb52-70a4-4bd6-be3b-8183a848d233.jpg)

![collector3](https://user-images.githubusercontent.com/74991451/207170593-284a55bb-c692-4d4d-ae5e-633a3a72b9f5.jpg)

![collector4](https://user-images.githubusercontent.com/74991451/207170718-052e88b9-cf8d-4f1c-9b90-cc59cc1cd534.jpg)

### Expected behavior

As I type each character in a filter, I would like the characters to correctly match what I am typing regarding collector, namespace, geographic area, determiner, etc.

### Environment

Sandbox

### Version

 build 64eba3530 on 2022-12-12T15:46:38Z

### Browser Used

Version 108.0.5359.99

**Comment by AntWeb-org** [comment] 2022-12-12 22:57
Changed username to @AntWeb-org 
@bpescador, @cgrinter, @rich-keller

**Comment by mjy** [comment] 2022-12-13 01:27
... I think this is a duplicate issue, will check.

**Comment by mjy** [comment] 2022-12-13 16:02
Duplicate of #3216.

**Closed by mjy** 2022-12-13 16:02 UTC
Labels: bug
