### ISSUE TITLE
Uniquify people modifies people names

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#2281] opened 2021-05-26 14:29 UTC
I just used uniquify people to merge names, and the name to which others were merged was modified.

So below are the names being merged Person 94222 does not have a prefix ,101451 which I am merging with the previous does.
![PreMerge](https://user-images.githubusercontent.com/70152690/119677740-f8eb7e80-be0c-11eb-873d-76dde7ad7d27.jpg)

After merging, the name retained now has a prefix
![postmerge](https://user-images.githubusercontent.com/70152690/119677903-19b3d400-be0d-11eb-9550-76c0244f383e.jpg)

This shouldn't happen correct? When names are merged together, it shouldn't combine field data from both entities being merged?

**Comment by mjy** [comment] 2021-05-26 14:31
Duplicate of @proceps issue.  It *does* merge data, idea being you if it's the same name then empty slots are filled when combined.

**Comment by debpaul** [comment] 2021-05-27 14:52
@kandakoj I see what you mean. Not sure (still learning) why "G.S." is in the prefix field in the first place? So the new record (that removes the extra "G.S.") looks better to me?

**Comment by mjy** [comment] 2021-05-27 15:01
I believe you are right @debpaul, just a bad entry that cascaded into a bad merge.

**Closed** 2021-08-06 01:21 UTC
Labels: bug
