### ISSUE TITLE
synonymize/validate family-group names / reaccommodate subordinate taxa automatically

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#681] opened 2018-11-22 18:19 UTC
Example 1, syonymize a tribe:
I make Conocephalomimini a synonym of Terpandrini. The type genus Conocephalomima remains in the hierarchy under Conocephalomimini and is not moved under Terpandrini. It keeps an invalid parent and is not shown among the genera of Terpandrini.
The validation states the problem: "Genus Conocephalomima is the type of tribe Conocephalomimini but it has a parent outside of Conocephalomimini"

Example 2, make a synonym tribe valid:
I make Ancylechini (a synonym of Holochlorini) a valid tribe of Phaneropterinae. The type genus Anylecha is not moved along but remains under Holochlorini, and Ancylechini appears without any subordinate genus in the hierarchy.
Validation: “Genus Ancylecha is the type of tribe Ancylechini but it has a parent outside of Ancylechini”

I think in both cases the involved genera should be moved automatically. In contrast to Example 1 most tribes include more than just one genus.

This is related to Issue #593 by MMCigliano (synonymize genus).

**Comment by proceps** [comment] 2018-12-03 22:36
If the list of children under a synonym taxon is large, it will be difficult to revert the automatic changes if they were done by mistake. All children taxa should be evaluated manually. Proposed solution. All required changes should be listed in the soft_validation section with a FIX button. Soft_validation_fixes are already available to resolve those issues.

After a Synonym relationship is created:
1. Display the button for the subject_taxon_name to change the parent of the taxon (if soft_validation find that change is needed).
2. Loop through all taxa which have subject_taxon_name as a parent, soft_validate them and offer a Button to move them to the valid parent (one by one, not all of them simultaneously)

If a Synonym relationship is destroyed:
1. Check for the type_species and type_genus relationship on the subject, soft_validate the type_species or the type_genus. Offer the soft_validation FIX button to move type to the valid taxon (previous subject_taxon_name).

**Comment by typophyllum** [comment] 2018-12-04 18:37
Thanks for responding. 

In the case of synonymizing a taxon, to evaluate all its children manually sounds a little bit cumbersome. I think this is not only a question of efficiency and time-saving for the editor, but also a matter of robustness and integrity of the data at any time. To leave a valid name under an invalid one is nomenclaturally impossible, in contrast to some of the other validation items.

I think to be able to manage a large database like OSF efficiently and reliably, as many aspects as possible of any nomenclatural change should be handled automatically (perhaps requiring the editor's confirmation in certain cases).

Could a to-be-synonymized taxon perhaps be provided with a memory of its children, in case a subsequent author comes along deciding to reinstate it as valid (or the editor in fact made a mistake)?

**Comment by typophyllum** [comment] 2018-12-11 14:07
"Invalid names cannot have subordinates, they will be synonyms of something else and all subordinate taxa will be moved there." (@proceps 4 days ago #645)

Imagine the following scenario:
I make a genus or a tribe a synonym. Before that, I had copied a list of its subordinates in a Word document. Then a power outage happens (unfortunately quite frequent here at the museum). The browser crashes and the Word document is lost because I failed to save it immediately. Power does not come back all day, and early next day I leave for a field trip.
If the subordinates of the recently synonymized taxon were not moved automatically to the new parent, they would be left in limbo. Perhaps for several days, perhaps I will even forget one or two when I try to reaccommodate these subordinates in case there are many. And it might take weeks or months until I detect the problem.
A nomenclatural change should by no means leave bad data behind, that the editor would need to fix manually. I do think that moving subordinates of a synonymized taxon automatically is indispensable.

**Comment by mjy** [comment] 2018-12-11 14:34
We're in agreement that the option to auto-move is needed on a per-project
enabling basis or a mechanism that prompts the user at the time of synonymy
to "move <stuff>", etc. can be added, or both.  We have an idea as to how
this could look in the existing new name task, we'll try and mock up that
interface here when we find time.  Whatever mechanism we create we also
need to allow the user to *not* move the taxa, as they may want to check
the effects on a per taxon basis, particularly when hundreds of names are
in play.  Either way, we'll come up with some clever interfaces to handle
the issue.

**Comment by mjy** [comment] 2019-05-25 13:53
Marking as a duplicate of #593.

**Closed by mjy** 2019-05-25 13:53 UTC
Labels: enhancement
