### ISSUE TITLE
Add asserted distribution annotation 

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#431] opened 2018-06-01 21:09 UTC
Add geographical annotation to assorted distribution.

When I say that this biological relationship is recorded in this publication from this geographic area.

**Comment by mjy** [comment] 2018-06-05 03:14
@proceps started working on this conceptually.  Going to take a bit to refactor AssertedDistribution, but I have the direction figured out.

**Comment by mjy** [comment] 2024-10-05 19:19
Now duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/4025

**Closed by mjy** 2024-10-05 19:19 UTC
Labels: enhancement, model
