### ISSUE TITLE
Distribution of synonyms should propagate

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1752] opened 2020-09-19 10:07 UTC
Holoscotolemon jaqueti (Corti, 1905) has its type-locality in Romania, county Prahova.
Here:
![image](https://user-images.githubusercontent.com/46284943/93664572-54779800-fa46-11ea-8b45-e67aa88a3199.png)

Metascotolemon granulatus Roewer, 1915 is a junior subjective synonym of the above. Its type-locality is is Romania, county Braşov.
Here:
![image](https://user-images.githubusercontent.com/46284943/93664553-3873f680-fa46-11ea-92e5-9f440b4e3b93.png)

Therefore, the distribution of this species should include both Braşov AND Prahova.
But this doesn't happen.
Here:

![image](https://user-images.githubusercontent.com/46284943/93664602-a02a4180-fa46-11ea-8447-27223860532b.png)

**Comment by mjy** [comment] 2020-09-19 14:44
Duplicate of #1570.  Should be live next week on Browse OTU

**Closed by mjy** 2020-09-19 14:44 UTC

**Comment by adrik29** [comment] 2020-09-19 15:50
Apologies for the double post.
Glad to see you are taking care of so many things at once...
