### ISSUE TITLE
Task - Browse taxon name - combination toggle is inconsistent 

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#387] opened 2018-04-19 19:19 UTC
It is possible to show hide combinations in such a way that some records remain hidden on a toggle.

**Comment by jlpereira** [comment] 2018-04-25 19:03
Can you provide an example of this?

**Comment by proceps** [comment] 2018-04-25 19:32
When you are on browse page, you click on the valid name, you have a valid label on the right side. When you click on the synonym, it is has an invalid label and the not which is the valid name. When you click on the combination, it shows the name as valid. It does not show what is the valid name for this combination.

**Comment by jlpereira** [comment] 2018-04-26 21:17
Thanks @proceps for the steps to reproduce it.

We're talking about the Browse Nomenclature task, right? Can you give me an example of an existing taxon and the db on sandbox where I can see and experiment with this?

**Comment by proceps** [comment] 2018-04-26 22:03
http://sandbox.speciesfile.org/tasks/nomenclature/browse/1760402
in the UCD 2018-04-13 00:58:47 -0500

**Comment by jlpereira** [comment] 2018-05-03 22:33
Thanks @proceps for the example. I pushed a fix for this, can you confirm if this is fixed?

**Comment by proceps** [comment] 2018-05-07 19:35
@jlpereira I cannot see any changes. When I click on the combination string, I still see the status of valid name.

**Comment by jlpereira** [comment] 2018-05-07 19:43
I think we're mixing different issues here. You mean this issue @proceps ? https://github.com/SpeciesFileGroup/taxonworks/issues/393

The fix was for the toggle problem with the filter

**Comment by jlpereira** [comment] 2018-05-07 21:28
The fix i made its was related a bug that you could display hidden/show data clicking on differents filters without check if another was already active

The duplicate labels probably is a problem related with turbolinks, I will check this.

In the example you provide, the combination is not hidden because the data attribute is data-history-is-subsequent="false" and the others is data-history-is-subsequent="true". Now its only hidden if that attribute is true. We should hide this without care the value of this attribute?

**Comment by jlpereira** [comment] 2018-05-07 21:37
Pushed a fix for this, now will hide data-history-is-subsequent without care the value

**Comment by proceps** [comment] 2018-05-07 22:41
I think you should take the value into the account. We have a separate toggle to hide combination, otherwise it will not make sense to have two. I know what is the problem. The dataset does not hove original citations assigned to the Combination. As I set, this is missing data in the original database.
I think you should revert the last change and close the case.
I will reopen it if I found further issues. Thanks

**Comment by jlpereira** [comment] 2018-05-07 22:53
I talked with @mjy about this and he said to hide history of each element with data-history-is-subsequent without care the value of the property. History and Combination filters will hide different information, but history will hide combination too i guess... not sure if this is a problem

Any suggestion here @mjy ?

**Comment by mjy** [comment] 2018-05-08 16:08
I'm likely a little confused, but this is the behaviour I'd expect:

* All combinations, relationships, protonyms should be hidden or not based on the corresponding button being clicked, regardless of is_subsequent or not, this should have top priority
* A seperate button should hide subsequent records *if* they still are displayed

**Comment by proceps** [comment] 2018-05-17 19:58
When I click history now, everything disappears, at least in 3i. I think it should be reverted based on data-history-is-subsequent="true" attribute.

**Closed as completed** 2018-05-22 17:00 UTC
Labels: bug
