### ISSUE TITLE
Data - Source - Edit 

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1014] opened 2019-07-23 16:52 UTC
I have a source with a Serial selected. When I click save the record, it is properly saved. I can preview the record.
I click the Edit button again. The Serial seams to be properly populated, but when I click Update record, the serial get destroyed (soft validation pops up).

**Comment by mjy** [comment] 2019-07-31 16:16
Duplicate of  #696 I think.

**Comment by proceps** [comment] 2019-10-02 15:59
Check this, it is quite critical, and should be easy to fix. 
When I edit source (which had serial selected), the serial is not populated back to form from the db, and once saved, the serial is destroyed.

**Comment by mjy** [comment] 2019-10-02 17:35
See #696.  we need to resolve the expected behaviour to fix this.

**Comment by proceps** [comment] 2019-10-02 18:06
it is not exactly related. In this case the serial is getting destroyed. The record which exists in the database (for) serial. Is not propagated into the form when you open edit. I do not see any overlap between Serial and verbatim. It seems all of this resolve properly in 3i project. Verbatim is overwritten if Serial exists. And this is an expected behavior.

**Closed** 2019-10-05 20:31 UTC
Labels: blocker, bug
