### ISSUE TITLE
Task - DwC-A Workbench - Record imports but Status remains errored.

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1951] opened 2020-12-15 22:01 UTC
See ant web data.  Not precisely sure what is going on here.  Brian will reload to try to replicate.

<img width="2561" alt="Screen Shot 2020-12-15 at 3 56 06 PM" src="https://user-images.githubusercontent.com/22600/102278045-bda86380-3eee-11eb-8814-8691a2a3e08e.png">

**Comment by LocoDelAssembly** [comment] 2020-12-15 22:56
If you click on "Errored" it displays what is the problem. It complains about ISO dates. These were run before supporting date ranges. Clicking Retry works. Naturally it would be insane to go one by one and #1950 needs to be solved.

**Comment by mjy** [comment] 2020-12-15 23:27
This is not that issue.  When I click on Erorred, then I am taken to the Specimen record.

**Comment by jlpereira** [comment] 2020-12-15 23:43
server?

**Comment by jlpereira** [comment] 2020-12-15 23:49
Nevermind, found it on sandsworm.

```
{
   "id":2817230,
   "status":"Errored",
   "metadata":{
      "error_data":{
         "messages":{
            "identifier":[
               "BLF1068(31)-01 already taken"
            ]
         }
      },
      "basisOfRecord":"PreservedSpecimen",
      "parse_results":{
         "virus":false,
         "hybrid":false,
         "parsed":true,
         "details":[
            {
               "uninomial":{
                  "value":"Mystrium"
               }
            }
         ],
         "quality":1,
         "bacteria":false,
         "verbatim":"Mystrium",
         "positions":[
            [
               "uninomial",
               0,
               8
            ]
         ],
         "surrogate":false,
         "normalized":"Mystrium",
         "cardinality":1,
         "nameStringId":"de2d7fad-b025-5059-b70a-de83ff50d3c2",
         "canonicalName":{
            "full":"Mystrium",
            "stem":"Mystrium",
            "simple":"Mystrium"
         },
         "parserVersion":"v0.14.1"
      },
      "imported_objects":{
         "collection_object":{
            "id":998013
         }
      }
   }
```

@LocoDelAssembly seems to be a backend issue, its importing the object but sending Errored as current status

**Comment by LocoDelAssembly** [comment] 2020-12-15 23:51
Yes, trying to figure out how is possible. It seems the CatalogNumber was rejected, but yet when browsing the collection object it does have one...

**Comment by LocoDelAssembly** [comment] 2021-01-18 16:43
I'm closing this for now, never got to reproduce the problem myself and seems it didn't happen again.

**Comment by LocoDelAssembly** [comment] 2021-08-30 22:04
@MJTPaleo just obverved this issue. Reopening.

**Closed** 2021-09-13 17:43 UTC
Labels: bug
