### ISSUE TITLE
Task - browse nomenclature - object radial - New combination

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1000] opened 2019-06-14 21:41 UTC
If in the object radial, I click New combination task, it should open black form in New combination. At the moment, it tries to open the task with protonym ID, and fails.

**Comment by mjy** [comment] 2019-06-14 21:52
Duplicate of #969

**Comment by proceps** [comment] 2019-06-14 21:58
Not related. 
#969 If I am on combination, and click edit button on the top of the page or in the ObjectRadial, I should be redirected to new combination, with this combination open for editing.
#1000 If I am on any taxonName (protonym or combination) and click New combination in the ObjectRadial, I should be redirected to a blank New combination task

**Comment by mjy** [comment] 2019-08-06 19:55
Should be fixed now.

**Closed by mjy** 2019-08-06 19:55 UTC
Labels: bug
