### ISSUE TITLE
Task - Browse nomenclature - radial object

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#969] opened 2019-05-07 16:35 UTC
If I am in browse nomenclature, and select a combination (click on it). When I click on Radial object for that combination, I suppose to get to Edit Combination task, but instead I am redirected to Edit TaxonName task

**Comment by mjy** [comment] 2019-05-24 18:13
Duplicate of #981

**Closed** 2019-08-09 15:36 UTC
Labels: bug
