### ISSUE TITLE
In Task - Collection objects by area and date range - cannot sort or click on objects in returned list

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1044] opened 2019-09-06 20:31 UTC
**Describe the bug**
When I search a set of found objects in the "Task - Collection objects by area and date range" e.g. Odonata with identifiers between "0-100", then I cannot sort by the column headers or double click on the objects returned to go to that collection object. 

**To Reproduce**
1. When I go to "Task - Collection objects by area and date range".
2. Then I search by any parameters to return any number of collection objects. 
3. And I try to sort by one of the headers "e.g. Catalog Number, Locality, etc ...". 
or 
3a. And I double click on one of the returned collection objects. 

4. Then nothing happens
Image of results after clicking on "Catalog Number" and on "Coleoptera 99"
![image](https://user-images.githubusercontent.com/11411328/64458456-fede8080-d0ba-11e9-82e0-f15db6d6d81d.png)

**Expected behavior**
The entire list should be sorted numerically or alphabetically by the appropriately selected column. 

or

I should be "shown" that Collection Object.

**Environment (please identify where you experience this bug:**
- Sandbox - Sandworm:
![image](https://user-images.githubusercontent.com/11411328/64458558-4a912a00-d0bb-11e9-9457-764f31526e76.png)

- Chrome 76.0.3809.132

**Comment by LocoDelAssembly** [comment] 2019-09-06 22:18
Probably the problem is the line below @mjy?
https://github.com/SpeciesFileGroup/taxonworks/blob/4a45db436257f0da6993f3ae7b65d35bc5edf455/lib/queries/collection_object/filter.rb#L223
And the record causing the query to fail https://sandworm.taxonworks.org/collection_objects/471112  (Identifiers - Insect Collection 40646.1).

```
An ActiveRecord::StatementInvalid occurred in filter#set_id_range:

  PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "40646.1"
: SELECT COUNT(DISTINCT "collection_objects"."id") FROM "collection_objects" LEFT OUTER JOIN "identifiers" ON "identifiers"."identifier_object_id" = "collection_objects"."id" AND "identifiers"."identifier_object_type" = $1 LEFT OUTER JOIN "repositories" ON "repositories"."id" = "collection_objects"."repository_id" LEFT OUTER JOIN "taxon_determinations" ON "taxon_determinations"."biological_collection_object_id" = "collection_objects"."id" LEFT OUTER JOIN "otus" ON "otus"."id" = "taxon_determinations"."otu_id" LEFT OUTER JOIN "taxon_names" ON "taxon_names"."id" = "otus"."taxon_name_id" WHERE (identifiers.type = 'Identifier::Local::CatalogNumber') AND (CAST(identifiers.identifier AS integer) between 0 and 100) AND "collection_objects"."project_id" = $2
  app/controllers/tasks/collection_objects/filter_controller.rb:65:in `set_id_range'
```

A quick fix would probably be cast to floating point, but preferably should be something that both deals with lexicographic sorting and be smart enough to detect numbers within text at the same time (don't know if Postgres has something built-in for this).

**Comment by tmcelrath** [comment] 2019-10-18 18:18
Comment - this should be rated as blocker. It is EXTREMELY time consuming to have to research everything.

**Comment by mjy** [comment] 2019-10-18 18:23
New filter completely replaces this page.  We just need final testing,
hopefully up very soon.

**Comment by tmcelrath** [comment] 2019-10-18 18:26
Related issue @mjy - containerized collection object identifiers do not appear alongside non-containerized ones in the results list. I also can't search for containerized identifiers and find them in the auto-complete list. Related? Fixed?

**Comment by tmcelrath** [comment] 2019-10-18 18:28
E.g. searching for "38390" in Browse Collection Object does not return "Insect Collection 38390" - which is a vial of Plecoptera with 31 individuals, 30 female, 1 male. I can find it if I search by its OTU - in Collection Object FIlter - so I know it is there, but that identifier doesn't display - you have to click through to see it.

**Comment by tmcelrath** [comment] 2019-10-18 18:55
Added the above issues as: #1143

**Comment by mjy** [comment] 2019-11-07 22:00
Resolved in new filter.

**Closed by mjy** 2019-11-07 22:00 UTC
Labels: bug
