### ISSUE TITLE
CSL file for book: Chalcidoidea of the World

### ISSUE THREAD

**Issue by JimWoolley** [SpeciesFileGroup/taxonworks#2368] opened 2021-07-27 14:59 UTC
Would it be possible to include a CSL file modified by Rachel Winston, to cover the CABI recommended format for the book, Chalcidoidea of the World, in the list of styles included in Filter Sources / Download Formatted?  

The CSL file is available at https://drive.google.com/file/d/1CV06ebKOxfJ2m7tSuqbv8-yco0eJLBbL/view?usp=sharing

I have also attached the CSL code as a text file.
[ChalcWorld-8Feb21-7.txt](https://github.com/SpeciesFileGroup/taxonworks/files/6886529/ChalcWorld-8Feb21-7.txt)

**Comment by mjy** [comment] 2021-07-27 16:34
Duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/2084

**Closed by mjy** 2021-07-27 16:34 UTC
