### ISSUE TITLE
CoL - CoLDP export fails with NoMethodError - undefined method `id' for false:FalseClass

### ISSUE THREAD

**Issue by gdower** [SpeciesFileGroup/taxonworks#2092] opened 2021-03-05 21:39 UTC
**Describe the bug**

The CoLDP exporter crashed while trying to export Orthoptera Species File latest sandcastle dump with the coldp_export branch. It might be because the taxon_name_id = 105 has 2 parents. Maybe this is bad data, but it probably also shouldn't crash the exporter.

**To Reproduce**
1. When I export genus Mirhipipteryx from the coldp_export branch
2. I get error `NoMethodError - undefined method 'id' for false:FalseClass`
3. byebug shows that o.parent_otu = false, and there's a code comment ` For OTUs with combinations we might have to change the parenthood?` The 105 taxon_name_id has 2 parents and one of them might be a combination:

![image](https://user-images.githubusercontent.com/8573609/110175248-176e4a80-7dc7-11eb-93b5-c32bcbea0311.png)

![image](https://user-images.githubusercontent.com/8573609/110169951-11746b80-7dbf-11eb-8688-7ef9bb050d94.png)

### byebug output
```
>> o.taxon_name_id
=> 105
>> o.parent_otu
=> false
>> o.parent_otu&.id
!! #<NoMethodError: undefined method `id' for false:FalseClass>
>>
```

### Console output:
```ruby
TaxonName Load (0.4ms)  SELECT "taxon_names".* FROM "taxon_names" INNER JOIN "taxon_name_hierarchies" ON "taxon_names"."id" = "taxon_name_hierarchies"."ancestor_id" WHERE "taxon_name_hierarchies"."descendant_id" = $1 AND ("taxon_names"."id" != 104) ORDER BY "taxon_name_hierarchies".generations ASC  [["descendant_id", 104]]
  Otu Load (0.1ms)  SELECT "otus".* FROM "otus" WHERE "otus"."taxon_name_id" = $1  [["taxon_name_id", 103]]
   (0.2ms)  SELECT COUNT(*) FROM "otus" WHERE "otus"."taxon_name_id" = $1  [["taxon_name_id", 103]]
   (0.1ms)  SELECT DISTINCT "sources"."id" FROM "sources" INNER JOIN "citations" ON "sources"."id" = "citations"."source_id" WHERE "citations"."citation_object_id" = $1 AND "citations"."citation_object_type" = $2  [["citation_object_id", 60], ["citation_object_type", "Otu"]]
  DataAttribute Load (0.2ms)  SELECT "data_attributes".* FROM "data_attributes" INNER JOIN "controlled_vocabulary_terms" ON "controlled_vocabulary_terms"."id" = "data_attributes"."controlled_vocabulary_term_id" AND "controlled_vocabulary_terms"."type" = $1 WHERE "data_attributes"."attribute_subject_id" = $2 AND "data_attributes"."attribute_subject_type" = $3 AND "controlled_vocabulary_terms"."uri" = $4 ORDER BY "data_attributes"."id" ASC LIMIT $5  [["type", "Predicate"], ["attribute_subject_id", 60], ["attribute_subject_type", "Otu"], ["uri", "https://api.catalogue.life/datapackage#Taxon.extinct"], ["LIMIT", 1]]
  DataAttribute Load (0.1ms)  SELECT "data_attributes".* FROM "data_attributes" INNER JOIN "controlled_vocabulary_terms" ON "controlled_vocabulary_terms"."id" = "data_attributes"."controlled_vocabulary_term_id" AND "controlled_vocabulary_terms"."type" = $1 WHERE "data_attributes"."attribute_subject_id" = $2 AND "data_attributes"."attribute_subject_type" = $3 AND "controlled_vocabulary_terms"."uri" = $4 ORDER BY "data_attributes"."id" ASC LIMIT $5  [["type", "Predicate"], ["attribute_subject_id", 60], ["attribute_subject_type", "Otu"], ["uri", "https://api.catalogue.life/datapackage#Taxon.temporal_range_end"], ["LIMIT", 1]]
  CACHE DataAttribute Load (0.0ms)  SELECT "data_attributes".* FROM "data_attributes" INNER JOIN "controlled_vocabulary_terms" ON "controlled_vocabulary_terms"."id" = "data_attributes"."controlled_vocabulary_term_id" AND "controlled_vocabulary_terms"."type" = $1 WHERE "data_attributes"."attribute_subject_id" = $2 AND "data_attributes"."attribute_subject_type" = $3 AND "controlled_vocabulary_terms"."uri" = $4 ORDER BY "data_attributes"."id" ASC LIMIT $5  [["type", "Predicate"], ["attribute_subject_id", 60], ["attribute_subject_type", "Otu"], ["uri", "https://api.catalogue.life/datapackage#Taxon.temporal_range_end"], ["LIMIT", 1]]
  DataAttribute Load (0.1ms)  SELECT "data_attributes".* FROM "data_attributes" INNER JOIN "controlled_vocabulary_terms" ON "controlled_vocabulary_terms"."id" = "data_attributes"."controlled_vocabulary_term_id" AND "controlled_vocabulary_terms"."type" = $1 WHERE "data_attributes"."attribute_subject_id" = $2 AND "data_attributes"."attribute_subject_type" = $3 AND "controlled_vocabulary_terms"."uri" = $4 ORDER BY "data_attributes"."id" ASC LIMIT $5  [["type", "Predicate"], ["attribute_subject_id", 60], ["attribute_subject_type", "Otu"], ["uri", "https://api.catalogue.life/datapackage#Taxon.lifezone"], ["LIMIT", 1]]
  Note Load (0.1ms)  SELECT "notes".* FROM "notes" WHERE "notes"."note_object_id" = $1 AND "notes"."note_object_type" = $2  [["note_object_id", 60], ["note_object_type", "Otu"]]
  Source Load (0.8ms)  SELECT DISTINCT "sources".* FROM "sources" INNER JOIN "citations" ON "sources"."id" = "citations"."source_id" WHERE "citations"."citation_object_id" = $1 AND "citations"."citation_object_type" = $2  [["citation_object_id", 60], ["citation_object_type", "Otu"]]
  TaxonName Load (0.3ms)  SELECT "taxon_names".* FROM "taxon_names" WHERE "taxon_names"."id" = $1 LIMIT $2  [["id", 105], ["LIMIT", 1]]
  Source Load (0.3ms)  SELECT "sources".* FROM "sources" INNER JOIN "citations" ON "sources"."id" = "citations"."source_id" WHERE "citations"."citation_object_id" = $1 AND "citations"."citation_object_type" = $2 AND "citations"."is_original" = $3 LIMIT $4  [["citation_object_id", 61], ["citation_object_type", "Otu"], ["is_original", true], ["LIMIT", 1]]
  TaxonName Load (1.1ms)  SELECT "taxon_names".* FROM "taxon_names" INNER JOIN "taxon_name_hierarchies" ON "taxon_names"."id" = "taxon_name_hierarchies"."ancestor_id" WHERE "taxon_name_hierarchies"."descendant_id" = $1 AND ("taxon_names"."id" != 105) ORDER BY "taxon_name_hierarchies".generations ASC  [["descendant_id", 105]]
  Otu Load (0.4ms)  SELECT "otus".* FROM "otus" WHERE "otus"."taxon_name_id" = $1  [["taxon_name_id", 104]]
   (0.6ms)  SELECT COUNT(*) FROM "otus" WHERE "otus"."taxon_name_id" = $1  [["taxon_name_id", 104]]
  CACHE  (0.0ms)  SELECT COUNT(*) FROM "otus" WHERE "otus"."taxon_name_id" = $1  [["taxon_name_id", 104]]
Completed 500 Internal Server Error in 1806054ms (ActiveRecord: 374518.0ms | Allocations: 580605879)



NoMethodError - undefined method `id' for false:FalseClass:
  lib/export/coldp/files/taxon.rb:145:in `block (2 levels) in generate'
  lib/export/coldp/files/taxon.rb:121:in `block in generate'
  lib/export/coldp/files/taxon.rb:101:in `generate'
  lib/export/coldp.rb:42:in `block (2 levels) in export'
  lib/export/coldp.rb:42:in `block in export'
  lib/export/coldp.rb:35:in `export'
  lib/export/coldp.rb:61:in `download'
  app/controllers/tasks/exports/coldp_controller.rb:12:in `download'

::1 - - [05/Mar/2021:13:53:45 CST] "GET /tasks/exports/coldp/download?utf8=%E2%9C%93&otu_id=&commit=Download&%5Botu_id%5D=52 HTTP/1.1" 500 92208
http://localhost:3000/tasks/exports/coldp -> /tasks/exports/coldp/download?utf8=%E2%9C%93&otu_id=&commit=Download&%5Botu_id%5D=52
Incoming Headers:
  Origin: http://localhost:3000
  Path-Info: /__better_errors/ad6f095f6a8b0eaf/variables
  Access-Control-Request-Method: 
  Access-Control-Request-Headers: 
Started POST "/__better_errors/ad6f095f6a8b0eaf/variables" for ::1 at 2021-03-05 14:23:51 -0600
::1 - - [05/Mar/2021:14:23:51 CST] "GET /favicon.ico HTTP/1.1" 200 0
http://localhost:3000/tasks/exports/coldp/download?utf8=%E2%9C%93&otu_id=&commit=Download&%5Botu_id%5D=52 -> /favicon.ico
  Source Load (0.7ms)  SELECT DISTINCT "sources".* FROM "sources" INNER JOIN "citations" ON "sources"."id" = "citations"
```

**Environment (please identify where you experience this bug:**
*** One of ***
- Native Arch install on the latest coldp_export branch with latest sandcastle dump restored

**Comment by mjy** [comment] 2021-03-05 21:40
Dupe of https://github.com/SpeciesFileGroup/taxonworks/issues/2011

**Closed by mjy** 2021-03-05 21:40 UTC
Labels: bug

**Comment by gdower** [comment] 2021-03-05 21:47
Thought I recognized those names. :facepalm: I'll just delete of the parents for now so that we can get a test dataset exported.

**Comment by mjy** [comment] 2021-03-05 21:48
This is a duplicated OTU per taxon name issue, i.e. a real scenariou we have to handle, will try to prioritize fixing this.
