### ISSUE TITLE
mapping OTU distribution to biogeographic realms

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3625] opened 2023-11-06 20:34 UTC
Request from Saad to be able to export distribution of higher taxa as mapped to Biogeographic realms.

**Comment by mjy** [comment] 2023-11-07 18:44
Duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/137

**Closed by mjy** 2023-11-07 18:44 UTC
Labels: task
