### ISSUE TITLE
Model - TaxonName - Procaryote names have broken rank validation

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2128] opened 2021-03-15 03:18 UTC
When I have a genus ranked name, and I try to assign it to a family parent, then I get an error message.  See screenshot.

![Screen Shot 2021-03-14 at 10 17 10 PM](https://user-images.githubusercontent.com/22600/111099288-32e9fb80-8513-11eb-989c-989181d8a107.png)

**Comment by proceps** [comment] 2021-03-15 04:02
I cannot replicate. Are you sure that both genus and family are covered by the same nomenclatural code?

**Comment by mjy** [comment] 2021-03-15 04:13
Aha.  Checking, nice idea.

**Comment by mjy** [comment] 2021-04-21 04:24
@proceps I think this is still a problem. 

![Screen Shot 2021-04-20 at 11 23 51 PM](https://user-images.githubusercontent.com/22600/115496537-7d0b7e80-a22f-11eb-8c82-07779ef2973c.png)

See argument in part here: https://pubmed.ncbi.nlm.nih.gov/29936290/

The names below this have ICN endings.

**Comment by mjy** [comment] 2021-04-21 04:34
@jlpereira @proceps the original issue here is indeed due to incompatible codes, however they can't be changed, in the current UI.

To replicate:

* create a Genus, attach to root, give it ICZN
* try to move that genus to a parent in ICN

We have two options:
1) we update the UI to let users switch codes, but only for names attached to root
2) we try to auto-switch the code when the name moves, this is likely more painful and I'm not sure I want to try and match ranks.

Thoughts?

**Comment by proceps** [comment] 2021-04-21 05:06
ICN is very restrictive for name ending for all ranks, that is why you have those error messages. Amoebozoa is a zoological name, if you want to put the group under ICN, the Myxomycetes as a ICN Class would make a good name. The cited paper actually proposes only to transfer Myxomycetes (not all Amoebozoa) under ICN.

If you switch code for a taxon under the Root, you have to switch the ranks for all children. and yes, you will need to match the ranks, which could be relatively easy for common ranks. But you should also remember the family group names, which have different endings under different codes, and all higher ranks are also regulated under ICN.

Switching the Code is not the only issue with the current model. If you create a Family or Order name and decide to change its rank to the Genus, you cannot. The rank change is allow only within one rank group, so you can change the rank from genus to subgenus, but not from family to genus. I think those restrictions are quite useful.

**Comment by proceps** [comment] 2021-07-27 17:21
should we close this?

**Comment by mjy** [comment] 2021-07-28 03:54
No, I think the problem still exists.

**Comment by proceps** [comment] 2022-11-19 00:25
duplicate of a recently closed issue

**Closed by proceps** 2022-11-19 00:25 UTC
Labels: bug
