### ISSUE TITLE
source save error

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#1718] opened 2020-09-04 16:53 UTC
**can't save an edit for a source**
**To Reproduce**
1. search for source Meyerdirk, D.E. & Moratorio, M.S. (1987a) Biology of |Anagrus giraulti| (Hymenoptera: Mymaridae), an egg parasitoid of the beet leafhopper, |Circulifer tenellus| (Homoptera: Cicadellidae). Annals of the Entomological Society of America 80(2), 272–277. [1987]
2. go to edit and fix italics marks (or whatever).
3. Cannot save - it says that Meyerdirk, D.E. & Moratorio, M.S. (1987a) is already taken (and there is only one)
4. the reference occurs in more that this project - is that the problem?

- Production
- Browser [e.g. firefox]

**Comment by mjy** [comment] 2020-09-04 16:56
Probably duplicate author year + letter (insert author year letters suck comment from me here) in another reference?

**Comment by JohnHeraty** [comment] 2020-09-04 16:57
No I checked that.

**Comment by mjy** [comment] 2020-09-04 17:06
Techniclly the reference is not in more than one project, it is duplicated:

![Screen Shot 2020-09-04 at 12 04 54 PM](https://user-images.githubusercontent.com/22600/92267848-f6c04900-eea6-11ea-8e34-80448dc51ce2.png)
 
So this is duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/364

**Closed by mjy** 2020-09-04 17:06 UTC
Labels: bug

**Comment by JohnHeraty** [comment] 2020-09-04 17:15
I thought out meant out of project??

**Comment by mjy** [comment] 2020-09-04 17:34
Out means out of project.

Sources are unique across all projects.
