### ISSUE TITLE
Task - Object Radial - for TaxonName

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#972] opened 2019-05-07 17:07 UTC
I am trying to delete a Taxon from the Browse Nomenclature page. I am getting a message "Taxon was successfully destroyed". But it is not, there are some data attached to the taxon which prevent deletion. Please make sure that the positive confirmation is provided only when the object is actually destroyed.

**Comment by mjy** [comment] 2019-05-14 19:45
Duplicate of #927

**Closed by mjy** 2019-05-14 19:45 UTC
Labels: bug
