### ISSUE TITLE
Uniquify People Filter doesn't return result

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#2528] opened 2021-09-16 16:56 UTC
**Describe the bug**
Searching for Last Name = "McElrath" in "Current Project" using Filter in Uniquify People. The screen just says loading and doesn't come back with a result.

![uniquifySearch_longwait](https://user-images.githubusercontent.com/2990155/133653166-e1f6639f-b755-46b4-baac-197c8b575d0b.png)

**Expected behavior**
I'd expect a rapid return of a hit.

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Firefox

**Need**
As a use case, I need this so that I can show how we (TaxonWorks) facilitate using Identifiers for People ...

**Comment by proceps** [comment] 2021-09-16 17:19
closed by mistake

**Comment by proceps** [comment] 2021-09-16 17:23
I never use left filter section. I always start with a correct person, and get redirected to uniquify task. In this case, I already have a first field pre-populated. Then, I use a search box, to find a second person. 
But I can confirm, the left filter does not work.
Small comment, in cases like 'McElrath' it is always better to search all projects, not just one.

**Comment by jlpereira** [comment] 2021-09-21 15:26
It doesn't seem to be an issue with the interfaces, for some reason the server is taking a lot of time to send the response
![Captura de pantalla de 2021-09-21 12-15-27](https://user-images.githubusercontent.com/16530364/134199834-9edc1fe9-c66b-4a1d-b245-21ba7ef064d4.png)

**Comment by mjy** [comment] 2021-09-21 15:54
This is because Tommy has many, many Roles.  Checking to see how to optimize.

**Closed** 2021-09-21 19:50 UTC
Labels: bug
