### ISSUE TITLE
Task - Filter staged images - by collection object [Was: Filter Options for the Collection object image breakdown (sqed) TODO list]

### ISSUE THREAD

**Issue by ggpagurus** [SpeciesFileGroup/taxonworks#3043] opened 2022-07-07 22:22 UTC
### Feature or enhancement

After uploading a new specimen image, I use the Collection object image breakdown (sqed) TODO list to find the recent upload and transcribe the labels and identifier codes.

Because there are several other people uploading to this project, it would be helpful if there was an option to filter the images by author/creator instead of hovering my cursor over each one to find my name.
<img width="1260" alt="Screen Shot 2022-07-07 at 6 19 15 PM" src="https://user-images.githubusercontent.com/108902839/177880971-bb23419f-fe43-4190-a938-8a138c1e76d4.png">
 

### Location

https://sfg.taxonworks.org/tasks/accessions/breakdown/sqed_depiction/todo_map

### Your role

Imaging Technician

**Comment by ggpagurus** [comment] 2022-12-14 19:51
Another idea is to add a link to the TODO list on the Browse collection object page

**Comment by mjy** [comment] 2022-12-14 19:56
Duplicate of #3171 in part.

**Comment by mjy** [comment] 2022-12-14 20:01
Include link from Navigate CO to Filter by CO id when this is implemented.

**Comment by mjy** [comment] 2023-02-24 21:03
Closing.  Staged image filter resolves the majority.

**Closed by mjy** 2023-02-24 21:03 UTC
Labels: enhancement
