### ISSUE TITLE
Can not enter PDF with size 35,4MB

### ISSUE THREAD

**Issue by PJansta** [SpeciesFileGroup/taxonworks#1263] opened 2019-12-20 19:41 UTC
**Hi, I can upload pdf which has 35,4MB of recently added source in production. Tried several times, no way. It always stop in around 30MB (see printscreen. Source is already saved.**

**To Reproduce**
1. When I  '...'
2. Then I '....'
3. And I '....'

<provide a screenshot>

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/58753011/71287584-993a9b00-231d-11ea-9e35-7ae7bedfa012.png)

**Environment (please identify where you experience this bug:**
*** One of ***
- 
- Production
- Browser - chrome

**Comment by mjy** [comment] 2019-12-20 19:52
@LocoDelAssembly @dimus This might be a nginx constraint.  Can we increase it to at least 125MB?

**Comment by LocoDelAssembly** [comment] 2019-12-20 20:37
Investigating what is happening. Using the docker image locally it fails too but doesn't log any error.

**Comment by LocoDelAssembly** [comment] 2019-12-20 21:22
Correction it works. It is just that the backend stays at 100% CPU usage for quite some time when uploading [Intel® 64 and IA-32 Architectures Software Developer’s Manual Combined Volumes: 1, 2A, 2B, 2C, 2D, 3A, 3B, 3C, 3D, and 4](https://software.intel.com/en-us/download/intel-64-and-ia-32-architectures-sdm-combined-volumes-1-2a-2b-2c-2d-3a-3b-3c-3d-and-4). When processing completes the document appears listed below. So docker image seems to be fine.

**Comment by LocoDelAssembly** [comment] 2019-12-21 06:40
Got debugging data and nginx blames the browser for terminating the connection. Nginx is right... https://www.dropzonejs.com/#config-timeout

With my upload speed of less than 800KB/s I'd need at least 35 seconds which exceeds the default timeout.

@jlpereira I'm not sure at which locations I should apply this setting so could you do it when you have a chance? I think setting this to zero will wait until upload completes or fails for some reason other than timing out. Since timeout is currently not being handled perhaps this is a better alternative than setting a large value.

@mjy increasing maximum upload size to 128MB (rounding your value to power of two) still holds?

**Comment by jlpereira** [comment] 2019-12-21 14:48
Try with the new timeout.

**Comment by mjy** [comment] 2019-12-21 15:33
@LocoDelAssembly yes I'd like to hit 128.

**Comment by LocoDelAssembly** [comment] 2019-12-21 15:46
![image](https://user-images.githubusercontent.com/4991925/71310095-d9b61980-23ee-11ea-8eda-7238a89dcd78.png)
@jlpereira it looks like other places need patching too. I tried changing zero to some other value but the xhr object still has 30000 ms timeout.

**Comment by mjy** [comment] 2019-12-21 15:54
If possible let's make this a "global"?

**Comment by jlpereira** [comment] 2019-12-21 15:58
Pushed, try now.
The problem is Dropzone is part of rails assets pipeline. We should replace it and install it as npm package.

**Comment by LocoDelAssembly** [comment] 2020-01-03 15:14
Applied fix on software side and recently on infrastructure config. Closing. Please @PJansta reopen if you still have problems with this.

**Closed by LocoDelAssembly** 2020-01-03 15:14 UTC
Labels: bug
