### ISSUE TITLE
[Bug]: DwC Occurrence Importer settings modal lags on open when many namespaces set

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2834] opened 2022-02-28 18:48 UTC
### Steps to reproduce the bug

When opening the DWC Occurrence Importer settings modal, each row in the list makes a namespace api query (if it is set/not blank).
If multiple rows are set to the same namespace, it generates duplicate queries which causes significant lag.

Ex: sandwich project Feb Antweb Import in the specimens import, it takes 10+ seconds to open the modal after clicking the button. (It also opens at the bottom of the list instead of the top)

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [X] Sandbox
- [ ] Production

### Sandbox Used

sandwich

### Version

all versions

**Comment by LocoDelAssembly** [comment] 2022-02-28 19:00
A bit hard to test because I'd need to interrupt your import. However closing the modal and opening settings seemed show up the modal in less than 2 seconds.

Can you reproduce the lag consistently?

**Comment by LordFlashmeow** [comment] 2022-02-28 19:02
You can test it while the import's in progress, just hide the import dialog. 

I'm getting it consistently, and I encountered it when running TW from my machine as well.

**Comment by LocoDelAssembly** [comment] 2022-02-28 19:06
Can I stop the import a bit and resume right after I test this?

**Comment by LordFlashmeow** [comment] 2022-02-28 19:08
Go for it. I'm pretty sure the problem is that each `Row` in Vue runs their own query instead of having something centralized that caches the responses.

**Comment by LocoDelAssembly** [comment] 2022-02-28 19:10
Please close any of your tabs, otherwise import starts again (need to fix this).

**Comment by LordFlashmeow** [comment] 2022-02-28 19:16
Done

**Closed** 2022-03-01 01:59 UTC
Labels: bug
