### ISSUE TITLE
Left T staged pattern

### ISSUE THREAD

**Issue by teleaslamellatus** [SpeciesFileGroup/taxonworks#3242] opened 2022-12-14 14:50 UTC
### Feature or enhancement

Some of our specimens are staged as left T. Currently, there is only an option for right T.

### Location

Task: New Image

### Your role

Imaging Technician

**Comment by mjy** [comment] 2022-12-14 14:58
Duplicate of #3204

**Closed by mjy** 2022-12-14 14:58 UTC
Labels: enhancement
