### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by teleaslamellatus** [SpeciesFileGroup/taxonworks#3186] opened 2022-11-07 17:36 UTC
### Steps to reproduce the bug

```bash
Filter collections object

1. check the identifier present

still will include specimens with missing identifiers

https://sfg.taxonworks.org/tasks/collection_objects/filter?per=500&page=1&georeferences=false&identifiers=true
```

### Screenshot

![image](https://user-images.githubusercontent.com/9273125/200377305-ebac8777-003a-4cab-a721-403a4e6f0fb7.png)

### Environment

Production

### Browser Used

chrome

**Comment by mjy** [comment] 2022-11-07 22:27
Duplicate of #3173.

**Closed by mjy** 2022-11-07 22:27 UTC
Labels: bug
