### ISSUE TITLE
CoL Import

### ISSUE THREAD

**Issue by sergeitarasov** [SpeciesFileGroup/taxonworks#3090] opened 2022-09-05 07:30 UTC
### Feature or enhancement

Hi,
I heard this request has been around in the TW community. It would be great to have a feature that allows importing taxon names (and their attributes) from Catalogue of Life directly into TW.  I know it's easier to say than to do... However, even a basic feature that imports taxon name + author & year in batch mode would be very handy.

Cheers, Sergei

### Location

/hub

### Your role

curator & TW user

**Comment by mjy** [comment] 2022-09-05 16:31
@sergeitarasov have you tried the TaxonNames -> Batchload -> Simple downloader in a pinch?  Could experiment with it in sandboxes.  It's limited, but useful for scaffolding, for example, the valid names you want to use in some clade.

Completely agree re CoL.   This, and many other external patterns need the following:

* A Ruby native wrapper on the API (typically, not always needed). We started a Ruby Gem to wrap the API- https://github.com/SpeciesFileGroup/colrapi.  If your team wants to contribute agnostic code to that gem, to add more parameters and tests, that would help.
* After that we need to write a middle-layer, taking the API response objects in colrapi and translating them to TW objects.   This is code that lives in `/lib/vendor` in TaxonWorks
*  The final step is figuring out the UI elements.  If you wanted to suggest the UI elements here, that would also help speed the process.

**Comment by mjy** [comment] 2022-09-05 16:32
..and now that I have commented, going to close this as duplicate of #1695

**Closed by mjy** 2022-09-05 16:32 UTC
Labels: enhancement

**Comment by sergeitarasov** [comment] 2022-09-05 18:58
Thanks, @mjy for the prompt reply! 
Yep, I wrote an R script that fetches taxon names from Gbif/CoL and converts them into a table that can be used to import names via TaxonNames -> Batchload -> Simple batch load. This way of importing includes a few manual steps, such as selecting the necessary file and parent taxon in TW each time when importing. This makes the import relatively slow. That's why I think having the import feature from within the TW would be useful.

Unfortunately, I do not know Ruby, but I would be happy to test the code or contribute in any other way :)

**Suggestions for UI elements:**
(the general idea may be similar to Batchload -> Simple batch load)

- _Search field_ that functions similarly to the [CoL search](https://www.catalogueoflife.org) concerning selecting a taxon name from the controlled vocabulary of CoL. Perhaps, this field should go along with the _radio element_ (options: i. search children; ii. search as it is) to confine the search to children names or use the input directly as the target name.
- _Search result table_ that summarizes the output of the search. It may have the following columns: name, rank, author, year, and hyperlink to CoL taxon. Plus, a checkbox for selecting the name(s) of interest to import.
- _Parent taxon field_ to select a taxon from the TW project that will be the parent for the imported names.
-  _Add button_ to commit the act of importing the selected names.

**Note:**
Minimal suggested attributes to import: name, author, year, CoL identifier. It would definitely grate to the extent the import to other data stored in COL but I suspect it is more complicated.
