### ISSUE TITLE
OTU List Download

### ISSUE THREAD

**Issue by gilliandubin** [SpeciesFileGroup/taxonworks#822] opened 2019-02-27 19:54 UTC
The download button on the list display of OTUs (under data) does not work.

**Comment by mjy** [comment] 2019-02-27 20:59
Steps to reproduce?  It works for me.  Your browser may be saving the file automatically depending on what your settings are.  Make sure it's not appearing in your recent downloads.

**Comment by gilliandubin** [comment] 2019-02-27 21:06
Dear Matt,

Thanks.

Sincerely,
Gillian Dubin

**Comment by mjy** [comment] 2019-02-27 21:21
Does this mean we can close the issue? :)

**Comment by gilliandubin** [comment] 2019-02-28 19:44
Dear Matt,

Yes. Sorry for the trouble.

Sincerely,
Gillian Dubin

**Closed** 2019-02-28 19:46 UTC
