### ISSUE TITLE
For all filters, have a facet that allows to filter for presence/absence of "notes" 

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#3065] opened 2022-08-03 16:09 UTC
### Feature or enhancement

When I am using the filter, it would be useful to be able to filter whatever data for the presence of "notes". 

### Location

All of the filters

**Comment by proceps** [comment] 2022-08-03 18:47
duplicate of #2771

**Closed by proceps** 2022-08-03 18:47 UTC
Labels: enhancement
