### ISSUE TITLE
Model - dwc_occurrence instances of collecting event with geographic areas not indicating coordinates are inexact

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#1175] opened 2019-11-08 11:29 UTC
When a collecting event is recorded with a geographic area rather than map coordinates, when the dwc_occurrence instance of such event is created, decimalLatitude and decimalLongitude are set to the center of the selected area with very high decimal precision, but there is no indication that such coordinates are inexact. This probably needs coordinateUncertaintyInMeters to be set. georeferenceProtocol might be useful as well, not sure.

**Comment by LocoDelAssembly** [comment] 2019-11-08 11:32
The example below is from Sandcastle, creating a fictitious specimen collected in Buenos Aires (TDWG area).
```
-[ RECORD 1 ]-----------------------+-------------------------------------------------
id                                  | 183
acceptedNameUsage                   | 
acceptedNameUsageID                 | 
accessRights                        | 
associatedMedia                     | 
associatedOccurrences               | 
associatedOrganisms                 | 
associatedReferences                | 
associatedSequences                 | 
associatedTaxa                      | 
basisOfRecord                       | PreservedSpecimen
bed                                 | 
behavior                            | 
bibliographicCitation               | 
catalogNumber                       | 
dwcClass                            | 
collectionCode                      | 
collectionID                        | 
continent                           | 
coordinatePrecision                 | 
coordinateUncertaintyInMeters       | 
country                             | 
countryCode                         | 
county                              | 
dataGeneralizations                 | 
datasetID                           | 
datasetName                         | 
dateIdentified                      | 
day                                 | 
decimalLatitude                     | -36.67974516447139
decimalLongitude                    | -60.55879052778007
disposition                         | 
dynamicProperties                   | 
earliestAgeOrLowestStage            | 
earliestEonOrLowestEonothem         | 
earliestEpochOrLowestSeries         | 
earliestEraOrLowestErathem          | 
earliestPeriodOrLowestSystem        | 
endDayOfYear                        | 
establishmentMeans                  | 
eventDate                           | 
eventID                             | 
eventRemarks                        | 
eventTime                           | -
family                              | Acrididae
fieldNotes                          | 
fieldNumber                         | 
footprintSRS                        | 
footprintSpatialFit                 | 
footprintWKT                        | 
formation                           | 
genus                               | Scotussa
geodeticDatum                       | 
geologicalContextID                 | 
georeferenceProtocol                | 
georeferenceRemarks                 | 
georeferenceSources                 | 
georeferenceVerificationStatus      | 
georeferencedBy                     | 
georeferencedDate                   | 
group                               | 
habitat                             | 
higherClassification                | 
higherGeography                     | 
higherGeographyID                   | 
highestBiostratigraphicZone         | 
identificationID                    | 
identificationQualifier             | 
identificationReferences            | 
identificationRemarks               | 
identificationVerificationStatus    | 
identifiedBy                        | 
individualCount                     | 1
informationWithheld                 | 
infraspecificEpithet                | 
institutionCode                     | MLP
institutionID                       | http://grbio.org/institution/museo-de-la-plata-0
island                              | 
islandGroup                         | 
kingdom                             | 
language                            | 
latestAgeOrHighestStage             | 
latestEonOrHighestEonothem          | 
latestEpochOrHighestSeries          | 
latestEraOrHighestErathem           | 
latestPeriodOrHighestSystem         | 
license                             | 
lifeStage                           | 
lithostratigraphicTerms             | 
locality                            | 
locationAccordingTo                 | 
locationID                          | 
locationRemarks                     | 
lowestBiostratigraphicZone          | 
materialSampleID                    | 
maximumDepthInMeters                | 
maximumDistanceAboveSurfaceInMeters | 
maximumElevationInMeters            | 
member                              | 
minimumDepthInMeters                | 
minimumDistanceAboveSurfaceInMeters | 
minimumElevationInMeters            | 
modified                            | 
month                               | 
municipality                        | 
nameAccordingTo                     | 
nameAccordingToID                   | 
namePublishedIn                     | 
namePublishedInID                   | 
namePublishedInYear                 | 
nomenclaturalCode                   | iczn
nomenclaturalStatus                 | 
occurrenceID                        | 
occurrenceRemarks                   | 
occurrenceStatus                    | 
order                               | 
organismID                          | 
organismName                        | 
organismQuantity                    | 
organismQuantityType                | 
organismRemarks                     | 
organismScope                       | 
originalNameUsage                   | 
originalNameUsageID                 | 
otherCatalogNumbers                 | 
ownerInstitutionCode                | 
parentEventID                       | 
parentNameUsage                     | 
parentNameUsageID                   | 
phylum                              | 
pointRadiusSpatialFit               | 
preparations                        | 
previousIdentifications             | 
recordNumber                        | 
recordedBy                          | 
references                          | 
reproductiveCondition               | 
rightsHolder                        | 
sampleSizeUnit                      | 
sampleSizeValue                     | 
samplingEffort                      | 
samplingProtocol                    | 
scientificName                      | Scotussa lemniscata (Stål, 1861)
scientificNameAuthorship            | (Stål, 1861)
scientificNameID                    | 
sex                                 | 
specificEpithet                     | lemniscata
startDayOfYear                      | 
stateProvince                       | 
subgenus                            | 
taxonConceptID                      | 
taxonID                             | 
taxonRank                           | 
taxonRemarks                        | 
taxonomicStatus                     | 
type                                | 
typeStatus                          | 
verbatimCoordinateSystem            | 
verbatimCoordinates                 | 
verbatimDepth                       | 
verbatimElevation                   | 
verbatimEventDate                   | 
verbatimLatitude                    | 
verbatimLocality                    | 
verbatimLongitude                   | 
verbatimSRS                         | 
verbatimTaxonRank                   | 
vernacularName                      | 
waterBody                           | 
year                                | 
dwc_occurrence_object_type          | CollectionObject
dwc_occurrence_object_id            | 96633
created_by_id                       | 1511
updated_by_id                       | 1511
project_id                          | 2
created_at                          | 2019-11-06 17:29:36.261336
updated_at                          | 2019-11-06 17:29:36.261336
```

**Comment by mjy** [comment] 2019-11-08 14:40
Partial duplicate of #915.  You are absolutely right about the protocol, we can use the Georeference::Type as a proxy.  I think we will not use error in meters (inferred) but rather cut the precision way down (3 decimals)?

**Comment by mjy** [comment] 2019-11-12 16:33
@LocoDelAssembly Two options, which do you prefer? 

* Find the max possible radius (i.e. max of length or width of the bounding box of the target polygon(s)) and provide that as `coordinateUncertaintyInMeters`?  It seems far less precise than the shape itself in some ways. 

* Should we just truncate the decimal points to like 3 or 4 and provide a method?

Maybe helps: [https://www.gbif.org/document/80536/biogeomancer-guide-to-best-practices-in-georeferencing](https://www.gbif.org/document/80536/biogeomancer-guide-to-best-practices-in-georeferencing)

**Comment by mjy** [comment] 2019-11-12 16:55
Aha, this is our answer I think: https://github.com/tdwg/dwc-qa/wiki/Georeferences#footprintwkt

**Comment by LocoDelAssembly** [comment] 2019-11-12 16:58
@mjy Sorry thought I replied this already but seems I did not... What I meant to reply was that truncation is not enough, for instance Buenos Aires spans several integer lat/lng.

**Comment by mjy** [comment] 2019-11-12 16:59
Right.  We will use `footprintwkt` I think

**Comment by LocoDelAssembly** [comment] 2019-11-12 17:04
If possible I'd use both, however it might be a bit heavier the use of footprintwkt if the polygon is not simplified, considering this is an attribute of every single record and it is not an ID but the full shape data.

**Comment by mjy** [comment] 2019-11-12 17:06
Both as in the first option (max radius) + footprint? 

We have to imagine how people will calculate on these downstream, if footprint, then they can derive the first option.

BTW, I'm not too worried about weight, but I get your point.

**Comment by LocoDelAssembly** [comment] 2019-11-12 17:31
I'm thinking on what people would see when using collection object filter, having something that is quick to see would be a plus. If not this then perhaps georeferenceRemarks explaining with a very short text that the coordinates are the center of the area, not actual location (if doesn't overwrite anything).

**Comment by mjy** [comment] 2019-11-12 17:33
I see.  I was thinking the DWC dump, not the UI response.  The latter will
almost certainly evolve as you suggest, including a map version.  We're
basically using the DWC dump as a proxy to see how far it will take us.

**Comment by mjy** [comment] 2020-09-24 21:15
New priority system/attribute mapping uses the most precise representation.  Geographic areas are in footprint.

**Comment by mjy** [comment] 2021-10-04 17:00
Double checking this, I might need to update serialization for GeographicAreas.

**Comment by mjy** [comment] 2021-10-04 17:03
When georeferencing is GeographicArea only, then metadata should come from here:

https://github.com/SpeciesFileGroup/taxonworks/blob/development/app/models/geographic_area/dwc_serialization.rb#L10

Closing for now.  Re-open with spec if an issue.

**Closed by mjy** 2021-10-04 17:03 UTC
Labels: enhancement
