### ISSUE TITLE
Task - Browse Taxon Name - in the relationships, add a hyperlink to an object taxon name

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#403] opened 2018-05-17 19:49 UTC
Hyperlink is needed on the object taxon name in relationships. When clicked, open browse nomenclature page of the appropriate taxon in the same Tab.

**Comment by mjy** [comment] 2018-05-17 20:41
Duplicate of #398

**Closed by mjy** 2018-05-17 20:41 UTC
Labels: enhancement
