### ISSUE TITLE
[Bug]: The green "fix" button in front of 

### ISSUE THREAD

**Issue by hhopkins77** [SpeciesFileGroup/taxonworks#2837] opened 2022-03-02 17:59 UTC
### Steps to reproduce the bug

```bash
1.
2.
3. 
...
```

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [ ] Sandbox
- [ ] Production

**Comment by proceps** [comment] 2022-03-02 22:14
duplicate of #2838

**Closed** 2022-03-31 16:58 UTC
Labels: needs more information
