### ISSUE TITLE
Task - Update Dockerfile to remove migration errors

### ISSUE THREAD

**Issue by devarsh1997** [SpeciesFileGroup/taxonworks#268] opened 2017-10-18 07:51 UTC
- In Docker and native installations, migration related issues arise during installation and testing TaxonWorks.
- Update the Dockerfile so that migration error does not occur when testing Docker version of TaxonWorks for the first time after installing.

**Comment by devarsh1997** [comment] 2017-10-22 01:53
Migration error is resolved in patched version of docker_compose_start.sh.

**Comment by mjy** [comment] 2017-10-23 21:01
Duplicate of #250

**Closed by mjy** 2017-10-23 21:01 UTC
Labels: bug, data migration, ready
