### ISSUE TITLE
Autocomplete - Author/Collector/People

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#2221] opened 2021-05-03 17:17 UTC
I think it would be very useful if People/Authors/Collector autocomplete could bring results with the same series of letters in the name or first name despite the accent mark it may have or other symbols.

Ex: If I look up for Stål, if I only write Stal it won't show up. Or Dérozier, if I write Derozier it won't find Dérozier. 
![image](https://user-images.githubusercontent.com/63611746/116909332-72cb8600-ac1a-11eb-90ac-8d185d7518ae.png)

Could this search ignore accent marks and so on to make the search more quick?

**Comment by proceps** [comment] 2021-05-03 17:27
you can do this now if you put alternative value on th author name. So, I put alternative spelling for Stal:
![image](https://user-images.githubusercontent.com/5597748/116910220-e82f5a80-ac0a-11eb-95a2-93864dec9d16.png)

**Comment by mabecabrera** [comment] 2021-05-04 21:07
Great! I was trying on Sandworm. It does not work like this there.

**Comment by LocoDelAssembly** [comment] 2021-05-04 21:17
Sandworm is up to date. Is it not working because alternate values are having problems or because there is no alternate spelling for Stål yet?

**Comment by proceps** [comment] 2021-05-04 21:30
Yes, I was using production.

**Comment by proceps** [comment] 2021-05-04 21:36
Added Stål into sandworm as an example.
![image](https://user-images.githubusercontent.com/5597748/117072879-bc899e80-acf6-11eb-9fa9-b2aaad5915ca.png)

**Comment by mjy** [comment] 2021-05-05 20:52
Can we close this?

**Comment by proceps** [comment] 2021-05-05 23:12
Unless there an elegant way to query database escaping diacritics... Or we cached the same name (or use alternative value) for the same names without diacritics automatically.

**Comment by LocoDelAssembly** [comment] 2021-05-05 23:34
Storing a cached "simplified spelling" could be a good idea! Maybe using something like https://www.rubydoc.info/gems/activesupport/2.3.17/I18n.transliterate?
```ruby
2.7.2 :003 > I18n.transliterate('Stål')
 => "Stal" 
```

**Comment by proceps** [comment] 2021-05-05 23:53
we can use alternative values for those, the Model already supports it. Could you check what happens to "Müller"? Is it converted to "Mueller"?

**Comment by LocoDelAssembly** [comment] 2021-05-06 00:00
```ruby
2.7.2 :007 > I18n.transliterate('Müller')
 => "Muller" 
2.7.2 :008 > I18n.transliterate('Müller', locale: :de)
 => "Muller" 
2.7.2 :009 > I18n.transliterate('Müller', locale: 'de')
 => "Muller" 
2.7.2 :010 > I18n.transliterate("Jürgen", :locale => :de)
 => "Jurgen" 
```
Doesn't seem to follow docs, unless they meant that I had to provide a translation file for the locale.

Not quite sure about using alternate values, you mean letting TW create them in `after_save` hook of Person model? But then those could be deleted by the user and also we have to make sure of taking them down if the user changes the name to something else that would make the alternate value no longer represent an adequate transliteration.

**Comment by proceps** [comment] 2021-05-06 00:08
There are only 3 umlauts, those could be treated before the translitiration. We still have all alternative values after people migration, many of those are misspellings. I do not think many people currate alternative spellings on people, those could not be accessed only in limited number of places. And useful mostly for search.

**Comment by LocoDelAssembly** [comment] 2021-05-06 00:18
I guess that if we add the following config (taken from docs):
```yml
# de.yml
i18n:
  transliterate:
    rule:
      ü: "ue"
      ö: "oe"
```
It would work. However, do we want this given that we want this only to aid search? Or perhaps we would need to store in cache all distinct values on all locales?

**Comment by proceps** [comment] 2021-05-06 00:25
add also ä: "ae". We will definitely hit the same problem on Source, CollectionObject, CollectingEvent, may be few other places...

**Comment by mjy** [comment] 2021-05-06 02:22
There should be no translation of the name by the model!  This splits where we do the work (it should be in alternate spelling, as noted).  The canonical name is the name in the native speakers language.  

The real thing we can do to improve is tweak the postgres text indexing, at the database side.

**Comment by mjy** [comment] 2021-05-06 02:24
I see, this is duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/879.

**Closed by mjy** 2021-05-06 02:24 UTC
