### ISSUE TITLE
[Bug]: Print label does not include Order or Family

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#4030] opened 2024-09-05 15:12 UTC
### Steps to reproduce the bug

```bash
1. When I try to print a label for Dorsiana semilata the label does not contain the bottom line, which should be the Order and Family. It is blank. For every other species in the same Genus there is no issue. So far it seems to just be this one label.
2.
3. 
...
```

### Environment

Production

### Browser Used

Chrome

**Comment by mjy** [comment] 2024-09-05 15:26
I suspect you selected the Combination ([c]) not the Protonym version of that name.  Can you try again to check?

**Comment by mmkohler** [comment] 2024-09-05 15:28
I tried several times with Tommy, and we couldn’t get it to work

**Comment by mjy** [comment] 2024-09-05 16:26
I just tried and confirmed that the issue is the selection of a Combination. See existing labels for it, and:

<img width="2182" alt="Screenshot 2024-09-05 at 11 23 41 AM" src="https://github.com/user-attachments/assets/c769bc0f-b0b0-4a95-9909-becd0c70d6ce">

I'll try and update the code to allow Combinations to work too.

**Comment by mjy** [comment] 2024-09-09 15:19
Fixed on next release.

**Closed by mjy** 2024-09-09 15:19 UTC
Labels: bug
