### ISSUE TITLE
New Source from Bibtex Author field populates, but authors disappear after Add Author then Click Save

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#2254] opened 2021-05-15 17:12 UTC
**Describe the bug**

Upon adding a **new source**, all fields appear to populate as expected. Author(s) **Verbatim From BibTex**  field contains expected values. But, after adding authors names in the Authors section and clicking Save, the names disappear from the  Authors **Verbatim From BibTex**  field.

Something about the **order** in which this is done seems to matter although I can't figure out what the order is.

See Also https://github.com/SpeciesFileGroup/taxonworks/issues/2255

**To Reproduce**
1. First, I uploaded **from BibTex** and all fields populated as expected.
2. Then I note I need to add authors 
3. And I (think I clicked Save), then started entering first author's name in the Author box and click "Add New"
4. Then the Author's name Does Not appear below in the beginning of the Author List as one would expect
5. And, Upon clicking save, (sometimes) the Verbatim From BibTex field changes to now have only this author in it, all others disappear.

(Additionally, and likely related, if I go now to add another Bibliographic Reference via BibTex, the Authors I've tried to add will add themselves to the new BibTex record when I click on Save).

Many screenshots (will zip).

**Expected behavior**
I'm not exactly sure about "expected behavior" but here goes.
1. After BibTex success, I need to enter all Authors (who may or may not be in the People records already)
2. In **New Source** > **Authors** does it matter if I'm on Quick/Recent/Pinboard/Search buttons? 
   - I've been on Quick or Search (for the most part).
3. I'd expect to search for the author string, if found, click it, and it would then appear in the author list.
4. I'd then repeat for all authors. 
5. IF an author isn't found, I'd expect to "Add New" AND then see it appear in the Author List.
   - this may be where the issue is because that's two actions (i.e. Add New, and Add to Author List). 

**Screenshots**
[TWscreenshots.zip](https://github.com/SpeciesFileGroup/taxonworks/files/6487831/TWscreenshots.zip)

**Environment (please identify where you experience this bug:**
- Sandbox - sandbox https://sandbox.taxonworks.org/tasks/sources/new_source
- Browser Firefox on a Win10 PC

**Comment by proceps** [comment] 2021-05-16 00:10
The form works as expected, once you add all authors as people roles (they are added as blue links) either searching and finding an existing person or adding a new one. Once you added all authors and seved the records, yes, the Bibtex field is replaced with new author string generated from all people added as authors. The same also works for editors. You do not need to save for each authors, you save only once when all authors are added to the list. You can also drag and drop authors to change the order. 
For the new bibtex record, please remember to use New button, otherwise you just modifying an existing record.

**Comment by proceps** [comment] 2021-05-16 00:12
Actually it would be nice to change "CrossRef" button to "New from CrossRef" expected behavior, a new record is created when parsed from Bibtex. I belive it is a common mistake, which could easily be avoided.

**Comment by mjy** [comment] 2021-05-17 15:27
Suggestions, reminding folks that our goal is to prioritize a small amount of learning as a cost to keep interfaces clean and uncluttered:

* `New: [ (CrossRef) (BibTeX) ]`, i.e. prefix with square brackets in lighter color, perhaps re-arranging position.
* Mouse-over tool tip (our prominent black style used in SV) with explanation
* Use orange help.

**Comment by debpaul** [comment] 2021-05-17 16:47
> For the new bibtex record, please remember to use New button, otherwise you just modifying an existing record.

@proceps I was using **New** for all of this testing.

**Comment by debpaul** [comment] 2021-05-17 16:50
> Actually it would be nice to change "CrossRef" button to "New from CrossRef" expected behavior, a new record is created when parsed from Bibtex. I belive it is a common mistake, which could easily be avoided.

@proceps it's confusing to see the Radio Buttons (where BibTex seems to be default), and then I click on "Cross Ref" and paste in a source DOI. So I'm not using BibTex directly as the Radio Button suggests.

**Comment by debpaul** [comment] 2021-05-17 16:52
> The form works as expected, once you add all authors as people roles (they are added as blue links) either searching and finding an existing person or adding a new one.

@proceps I don't think this workflow path is clear / intuitive in the interface. You mean I must do "A" before "B?" How does the interface communicate that?
A = Add all authors as people
B = Choose the authors for the specific Source

**Comment by proceps** [comment] 2021-05-17 17:52
The authors are created inline, you do not need to do anything species before adding new source. When you search for a person to add as an author, and the author is not found, you have a button to add theis authors as a new person, and simultaniously add this new person as an author to the source. 
I never used radio button. But I gues you can create a person as a source of data (a personal communication).

**Comment by debpaul** [comment] 2021-05-17 18:49
> 
> 
> The authors are created inline, you do not need to do anything specific before adding new source. When you search for a person to add as an author, and the author is not found, you have a button to add theis authors as a new person, and simultaniously add this new person as an author to the source.
> I never used radio button. But I gues you can create a person as a source of data (a personal communication).

@proceps this process you describe above (where I have a "button to add authors, and add simultaneously) is what I did, but didn't work. As I describe above.

**Comment by proceps** [comment] 2021-05-17 19:04
![image](https://user-images.githubusercontent.com/5597748/118542246-5fd7ac00-b718-11eb-8647-73ba7b129a63.png)

Author created but source is not saved

![image](https://user-images.githubusercontent.com/5597748/118542381-8e558700-b718-11eb-834a-68233d700816.png)

Souce saved

![image](https://user-images.githubusercontent.com/5597748/118542524-bcd36200-b718-11eb-9c84-084eea2d2604.png)

**Comment by mjy** [comment] 2021-05-18 15:03
The major issue here is the major issue outstanding bit of confusion with the form:

> And, Upon clicking save, (sometimes) the Verbatim From BibTex field changes to now have only this author in it, all others disappear.

Let's define somethings:
* `authors` - lowercarse, the verbaitm BibTeX field
* `Authors` - uppercase,  the People instances in TW that authored the paper
* `Roles` - uppercase, the links between People and the Source, have different types
* `Person` - An instance of a person in TW, can get orcids, identifiers, etc.

* When you add BibTeX then you populate `authors`.
* When you have `authors` the default citation is _rendered_ using `authors`
* When you add `Author` then you are asserting a much useful bit of information, you are linking to a Person.
* When you link to a Person then we assume it's best to _render_ the default using the up-to-date information on that Person
* When we render using the best information then we _replace_ `authors` with the information that came from Author/Person, because this should be more up-to-date
* (here is the problem) _When we save the Source *before* all Authors are added to the list, then we prematurely erase `authors` and we do not know who else we were supposed to add.

Once you learn how this works (it's straightforward) you add all Authors before saving.  _This doesn't make this not a real problem, it is._

Clever solution: 
* Detect, client side, that there the n people in `authors` != the m people in `Authors` and prevent save until thi sis finished.

@jlpereira The check can be made by  comparing `Author` count to the number of ` and ` + 1 in `authors` (` and ` is what BibTeX uses to divide authors in the author string)

**Comment by proceps** [comment] 2021-05-18 15:10
You cannot just prevent saving, the bibtex fields may also have errors. You can only provide a warning message. The best solution would be to never overwrite "Bibtex authors" and use it as a reference (that what we do for the journal string). But give Authors from people a preference, when generating a cached value.

**Comment by mjy** [comment] 2021-05-18 20:37
It would be a pain to do that because it breaks the BibTeX libraries that we use to handle the data.  It is possible, but still won't resolve the awkwardness we have here.

**Comment by proceps** [comment] 2021-05-18 20:48
add verbatim_author string which is generated on CrossRef processing, and use bibtex_authors for all other means. You can even completely hide bibtex_author field, since it is only will be used for calculation.

**Comment by mjy** [comment] 2021-05-18 20:49
We may have to do something like that, but we still have to write exceptions because bibtex processing maps to bibtex fields, so we have to catch it coming in, or out.  Then we have to sync 3 fields instead of 2.

**Comment by proceps** [comment] 2021-08-06 15:54
should we close this?

**Closed** 2021-11-09 21:15 UTC
Labels: bug
