### ISSUE TITLE
Option to invite new user to project

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2727] opened 2021-12-15 22:32 UTC
### Feature or enhancement

When I want to invite a new user to TaxonWorks, I have to go `/signup` and fill out information for them, including a temporary password. Instead of making a password for them or having them go through the "forgot password" process, I want a button that sends them an email informing them they've been invited and prompting them to create a password

### Location

On the new user page (`/signup`)

### Your role

Project admin

**Comment by mjy** [comment] 2021-12-21 15:29
Duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/10

**Closed by mjy** 2021-12-21 15:29 UTC
Labels: enhancement

**Comment by LocoDelAssembly** [comment] 2021-12-21 16:03
Not truly duplicate, but implementing this would require granting user creation privileges to project administrators or enable this feature only to administrator users. Also, I guess that the title implies user auto-join to project and would actually be a different endpoint rather than main `/signup`.

**Comment by mjy** [comment] 2021-12-21 16:05
All true @LocoDelAssembly, I just feel we should consider this under the umbrella of #10 (other considerations).

**Comment by mjy** [comment] 2021-12-21 16:16
Project administrators already have user creation privledges. So the only change required is to create a link to the password reset/set form.  We could use the same form, with a different header (Reset/set)?

**Comment by LordFlashmeow** [comment] 2021-12-21 16:20
The feature I had in mind was for the new user to get a friendly email inviting them to the project, instead of the unformatted (ugly) password reset message.

**Comment by mjy** [comment] 2021-12-21 16:22
Right, different email, but "same" password setting interface.
