### ISSUE TITLE
DWCA importer feedback - import stalls with large datasets

### ISSUE THREAD

**Issue by adeans** [SpeciesFileGroup/taxonworks#2053] opened 2021-02-18 19:08 UTC
I tried uploading a large dataset (~130k occurrences) on sandworm. The process seemed to be "active" -- i.e., the TaxonWorks icon is animated, and the message reads "Importing rows ... please wait". The numbers don't change, though, after a couple hours(?) of whirring.

<img width="750" alt="Screen Shot 2021-02-18 at 2 03 37 PM" src="https://user-images.githubusercontent.com/8043009/108407953-72fade80-71f2-11eb-9eb5-141d6b707503.png">

When I click "stop import" and then click "start import" it seems to start up again.

**Comment by mjy** [comment] 2021-02-18 19:29
@jlpereira @LocoDelAssembly I'm wondering if client is getting interupted and not recovering gracefully?  Is it polling the import process?  

Thoughts: as a curator I want to be able to start the process and
* Switch tabs in the browser without stopping the process
* Close a tab in the browser without stopping the process (do we want this)?
* Click on a dataset and re-engage the progress bar.

**Comment by LocoDelAssembly** [comment] 2021-02-18 19:42
If the tab was open all the time (even on background) it should have made progress. Note sure how connections errors are handled @jlpereira?

**Comment by jlpereira** [comment] 2021-02-18 19:54
On error response a generic alert should be displayed and the spinner should stop. This is something we need to test to know what its happen. Im switching to DWC branch to look it more closely

**Comment by jlpereira** [comment] 2021-02-18 21:25
@adeans at some point during the import process, did the computer go into sleep mode?

**Comment by adeans** [comment] 2021-02-18 21:27
@jlpereira likely yes, it probably did go to sleep

**Comment by LocoDelAssembly** [comment] 2021-02-18 21:31
@adeans which browser are you using?

**Comment by jlpereira** [comment] 2021-02-18 21:39
I can confirm the problem is related with the sleep mode

**Comment by adeans** [comment] 2021-02-18 21:47
@LocoDelAssembly Chrome Version 88.0.4324.182 (Official Build) (x86_64) for this particular upload

**Comment by LocoDelAssembly** [comment] 2021-02-18 22:02
Perfect thanks. @jlpereira found https://w3c.github.io/screen-wake-lock/ which should work in your setup (doesn't work for Firefox). But we are also checking other entirely new import mechanism making unnecessary to leave open the importer. Will fix this one way or another.

**Comment by LocoDelAssembly** [comment] 2021-07-14 20:54
This should be already be fixed when importing via ActiveJob was implemented. Closing.

**Closed by LocoDelAssembly** 2021-07-14 20:54 UTC
