### ISSUE TITLE
Task - New Taxon Name - Author list

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#226] opened 2017-09-13 23:52 UTC
Situation: we have a taxon associated with the original publication. Publication has a list of authors (Author1, Author2, Author3). All authors are separated as roles. So that publication has 3 associated people. A Taxon has different author list (Author3, Author1). 

Proposed design: In the tab Author/Person add a button 'Copy from the source'. 
Pushing this button copies 3 roles to the TaxonName authors. After that, the list of people could be reordered and some of the authors could be deleted from the list.

**Comment by mjy** [comment] 2018-10-29 19:34
Duplicate of #178

**Closed by mjy** 2018-10-29 19:34 UTC
Labels: enhancement
